### ISSUE TITLE
Mutation with EF model object as parameter

### ISSUE THREAD

**Issue by mscrocdile** [ChilliCream/graphql-platform#5022] opened 2022-05-03 07:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This 
```
public Customer AddCustomer(Customer customer)
        {
            ctx.Customers.Add(customer);
            ctx.SaveChanges();
            return customer;
        }
```
results to that graphql mutation query requires customer.id which is primary key.
mutation {
  addCustomer(customer: {email:"abc@cde.ef",name:"xy"}) {
    id, name
  }
}
In this case i don't want to pass Customer.ID at all.
Is there any workaround (without need to create new input type) or it is simply not possible?

### Steps to reproduce

1. Create mutation function with any EF model with primary key as a parameter.
2. create mutation query
3. Error that ID is required parameter appears.

### Product

Hot Chocolate

### Version

12.8.1

**Comment by rhyshamilton** [comment] 2022-05-04 09:28
As per the [docs](https://chillicream.com/docs/hotchocolate/defining-a-schema/mutations), it is best practice for Mutations to contain a single argument called `Input`.  

However, you don’t need to create these manually! 

HotChocolate allows you to opt in to the `AddMutationConventions` when configuring your GraphQL server.

```
service
    .AddGraphQLServer()
    .AddMutationConventions(applyToAllMutations: true)
```

(The `applyToAllMutations: true` is optional, but I personally recommend it)

Then, all you’d need to do is adjust your method to only include the properties you want (e.g – email and name)

`public Customer AddCustomer(string email, string name, ...) `

If you prefer, you can still always create your own inputs, but with the `AddMutationConventions`  you don’t necessarily have to.

Hope this helps :)

**Comment by mscrocdile** [comment] 2022-05-04 10:52
Conventions... clear.
However if i want to do this:
public Customer AddCustomer(Customer c) 
and
public Customer UpdateCustomer(Customer c)
In mutation query I thought it is somehow possible that UpdateCustomer expect Customer.ID and in AddCustomer doesn't.
Simply modify EF model or tell it to framework somehow. 
To avoid parameters duplications or creating similar models outside EF.
Thank you

**Comment by cts-tradeit** [comment] 2022-06-16 09:10
1) Declate InputObject<YourEntityClass> and mark field id as nullable. However you will have to manually validate in each mutation that id is or is not filled.

OR

2) Create two classes UpdateYourEntityInput and CreateYourEntityInput which both inherit your entity and mark property id ignored by attribute (not sure if attribute exists) or using option 1. This produces two separate input which are both assignable to YourEntity in C# and can be directly added to EFC (which recognises that it's suppose to save it as parent type as EFC scans inheritance for non-configured types to find configured type).

**Comment by michaelstaib** [comment] 2024-12-11 14:04
I am closing this issue as it is not a bug. There are several ways to solve this, from using a type to specify which parts are ignored in the input case. Another good solution might be to have a separate model for the input case that also encapsulates validation.

**Closed by michaelstaib** 2024-12-11 14:04 UTC
Labels: 🌶️ hot chocolate
