### ISSUE TITLE
Different responses for unathorized/forbidden using [Authorize] attribute.

### ISSUE THREAD

**Issue by Lanshir** [ChilliCream/graphql-platform#6326] opened 2023-07-07 12:17 UTC
### Product

Hot Chocolate

### Is your feature request related to a problem?

When using current Authorize attribute with Roles it returns AUTH_NOT_AUTHORIZED for both unauthorized and roles mismatch cases, which makes it impossible to determine if user needs to be redirected to login form (or renew token), or just see something like "you have no rights here" message.

### The solution you'd like

Would be good to have different AUTH_NOT_AUTHORIZED / AUTH_FORBIDDEN codes for authorization/policy mismatch like 401 and 403 http codes.

**Comment by holotrek** [comment] 2023-09-13 21:31
I would like to see this option too. I feel like this is a must have in order to allow the client to appropriately respond to a 401/403 code rather than if there were truly a 500 exception.

As an example, I am using StrawberryShake from Blazor WASM to hit my GraphQL server and I added a Polly policy to retry on 5xx errors like so:
```c#
// Retry GraphQL requests up to 4 times, with exponentially increasing delays
var policy = HttpPolicyExtensions
    .HandleTransientHttpError()
    .WaitAndRetryAsync(4, retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)));

// Add GraphQL Client
builder.Services
    .AddGraphQLClient()
    .ConfigureHttpClient(
        client => client.BaseAddress = new Uri($"{builder.HostEnvironment.BaseAddress}graphql"),
        clientBuilder => clientBuilder.AddPolicyHandler(policy)
    );
```

However, if the user is unauthorized, I simply want it to fail and send them to the login page rather than retrying.

**Comment by KarachoCake** [comment] 2023-09-15 08:13
I'm using the [Authorize(Policy = "Admin")] variant along with NTLM authentication, and I'm encountering a similar problem. In particular, when a user lacks the necessary permissions (e.g., not in the "Admin" role), it results in a 401 Unauthorized status code.

When using the Edge browser, end users are repeatedly prompted to re-enter their credentials as long as a 401 status is returned.

It would be incredibly helpful if Hot Chocolate could differentiate between unauthorized access (e.g., when a user isn't authenticated at all) and cases where the user lacks specific permissions.

Is there perhaps a workaround to return a 403 Forbidden status code in scenarios where authorization fails due to insufficient roles or policies? This would be especially beneficial in scenarios like mine where NTLM authentication is used.

**Comment by epbensimpson** [comment] 2023-09-25 03:19
The `AuthorizeMiddleware` already handles `AuthorizeResult.NotAuthenticated` however, the `DefaultAuthorizationHandler` never returns that value for some reason. I worked around it by making my own version of `DefaultAuthorizationHandler` and having it take the authenticated status into account when deciding which result to return.

e.g. 
```csharp
foreach (var directive in directives)
{
    var result = await AuthorizeAsync(
            user,
            directive.Policy,
            directive.Roles,
            authenticated,
            context)
        .ConfigureAwait(false);

    if (result is not AuthorizeResult.Allowed)
    {
        return result;
    }
}

return AuthorizeResult.Allowed;
```

Becomes
```csharp
var result = AuthorizeResult.Allowed;

foreach (var directive in directives)
{
    result = await AuthorizeAsync(
            user,
            directive.Policy,
            directive.Roles,
            authenticated,
            context)
        .ConfigureAwait(false);

    if (result is not AuthorizeResult.Allowed)
    {
        break;
    }
}

return result is AuthorizeResult.Allowed || authenticated ? result : AuthorizeResult.NotAuthenticated;
```

Would really like proper support for this though 🙏

**Comment by SebastianAchatz** [comment] 2023-11-16 19:01
That's an issue for us too. Would be great to have a built in solution and not to "patch" the DefaultAuthorizationHandler

**Comment by onionhammer** [comment] 2023-11-30 16:10
AUTH_NOT_AUTHORIZED is way too overloaded.. for us it could mean we couldn't find the user in our system (but the JWT is valid) or it could mean that the user is not authenticated at all (no JWT/bad JWT) or it could mean the user is authenticated and their account exists but they tried to do something they shouldn't

**Comment by onionhammer** [comment] 2023-11-30 19:27
> I worked around it by making my own version of `DefaultAuthorizationHandler` and having it take the authenticated status into account when deciding which result to return.

FYI, I dont think this covers every case. I also added this code:

![image](https://github.com/ChilliCream/graphql-platform/assets/969938/4ec6d597-97a0-436b-be47-46dc6a947369)

**Comment by glen-84** [comment] 2024-02-18 11:28
Closing as a duplicate of #6228.

**Closed by glen-84** 2024-02-18 11:28 UTC
Labels: 🐾 duplicate, 🎉 enhancement, 🌶️ hot chocolate, Area: Authorization
