### ISSUE TITLE
No way to access underlying ClientWebSocket in Strawberry Shake (e.g. to set auth headers)

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#6910] opened 2024-02-16 15:47 UTC
### Product

Strawberry Shake

### Version

14.0.0-p.35

### Link to minimal reproduction

See below

### Steps to reproduce

This is a docs bug.

The [Strawberry Shake auth docs](https://github.com/ChilliCream/graphql-platform/blob/main/website/src/docs/strawberryshake/v13/networking/authentication.md) says that `IWebSocketClient` provides access to the underlying `ClientWebSocket`. It does not; it only provides access to `Socket`:

https://github.com/ChilliCream/graphql-platform/blob/8717279ad915f224867d1f82b4b553bab3daabf6/src/StrawberryShake/Client/src/Transport.WebSockets/IWebSocketClient.cs#L9-L15

With `Socket`, it is not possible to set headers, because there is no `Options`. The docs should be updated. **Also, how can I set headers currently?**

### What is expected?

A way to set headers on socket connections.

### What is actually happening?

No discernible way to set headers on socket connections.

**Comment by glen-84** [comment] 2024-02-16 19:23
Duplicate of #6052.

**Closed by glen-84** 2024-02-16 19:23 UTC
Labels: 🐛 bug, 🐾 duplicate, 📚 documentation, 🌶️ strawberry shake
