### ISSUE TITLE
Using same method names breaks schema with UseOffsetPaging in v13

### ISSUE THREAD

**Issue by Archomeda** [ChilliCream/graphql-platform#5914] opened 2023-03-03 13:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When having two methods with the same name in a query class, UseOffsetPagingAttribute seems to reuse the CollectionSegment, resulting in an invalid schema if these methods return different types.

I have noticed that this is mentioned as a [breaking change in v13](https://chillicream.com/docs/hotchocolate/v13/migrating/migrate-from-12-to-13/#useoffsetpaging), however I would say that this change is actually also unexpected and unwanted behavior. This is especially the case when removing the UseOffsetPagingAttribute, then suddenly the schema does follow the return type (or better explained when you want to go from non-paged to paged by adding the attribute, and then not notice that the type is incorrect).

And yes, I have noticed the InferCollectionSegmentNameFromField setting, but I would rather not have to explicitly set a behavior for something that shouldn't be a problem in the first place (not mentioning the fact that I don't know if this option will be removed in the future or not). Also, this property only seems to exist as a global setting, and not in the UseOffsetPagingAttribute as the migration docs seem to suggest.

### Steps to reproduce

Have the following code and generate or browse the schema:

```cs
public class Dog
{
    public string DogName { get; set; } = null!;
}

public class Cat
{
    public string CatName { get; set; } = null!;
}


public class AnimalQuery
{
    [UseOffsetPaging(IncludeTotalCount = true, MaxPageSize = 100)]
    public IQueryable<Dog> GetCats()
    {
        throw new NotImplementedException();
    }

    public InnerFixedQuery Fixed { get; set; } = new();
}

public class InnerFixedQuery
{
    [UseOffsetPaging(IncludeTotalCount = true, MaxPageSize = 100)]
    public IQueryable<Cat> GetCats()
    {
        throw new NotImplementedException();
    }
}
```

Observe that both the endpoints have the `CatsCollectionSegment`, whereas v12 would generate `DogsCollectionSegment` and `CatsCollectionSegment`.

Note that Dogs and Cats are just for demonstration purposes, we internally reuse certain words as methods like GetMetrics in different subqueries with different return types, which explains the use case a lot better.

### Version

13.0.5

**Comment by michaelstaib** [comment] 2023-03-03 17:24
The reason for this are aggregations. When putting aggregations on the paging types its important to know the context which is better inferred from the field.

However, you can override this behavior globally and per field and even override the name of the connection.

This is not a bug but gives more control to the implementor. This change has been done to the cursor pagination now for over a year and this change just aligns both variants.

I am closing this issue as it is not a bug.

In order to change default behavior do this:

```csharp
.SetPagingOptions(new() { InferConnectionNameFromField = false });
```

**Closed** 2023-03-03 17:24 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, Area: Data

**Comment by Archomeda** [comment] 2023-03-03 17:40
Odd design decision because in my opinion there's no gain on either variant, and there are downsides to both. And because InferConnectionNameFromField is **actually not** available on UseOffsetPagingAttribute (as I've also mentioned in my message) it really felt like an oversight.

**Comment by michaelstaib** [comment] 2023-03-03 18:09
I will have a look at the attributes so we can refine this.
