### ISSUE TITLE
Active Persisted Query Pipeline not persisting query

### ISSUE THREAD

**Issue by jamsch0** [ChilliCream/graphql-platform#1365] opened 2020-01-09 23:24 UTC
**Describe the bug**
When using Active Persisted Query execution pipeline, queries are never persisted.

**To Reproduce**
1. Enable APQ [as per docs](https://hotchocolate.io/docs/10.3.1/persisted-queries#active-query-persistence), including SHA256 hashing.

```cs
services.AddGraphQL(
    serviceProvider => SchemaBuilder.New()
        // ...
        .Create(),
    queryExecutionBuilder => queryExecutionBuilder
        .AddSha256DocumentHashProvider()
        .UseActivePersistedQueryPipeline());

services.AddFileSystemQueryStorage();
```

2. Use Apollo client with `apollo-link-persisted` to make query (using SHA256 hashing by default).

![image](https://user-images.githubusercontent.com/1948214/72113152-92f57880-3337-11ea-81d2-60c62734124d.png)

3. First response from server returns `PERSISTED_QUERY_NOT_FOUND_ERROR`, as expected.

![image](https://user-images.githubusercontent.com/1948214/72113166-9d177700-3337-11ea-91ed-c443f16a2df5.png)

4. Client then resends with full query, and server responds with data but no `"extensions"` section or has (as if APQ is disabled).

![image](https://user-images.githubusercontent.com/1948214/72113109-69d4e800-3337-11ea-9679-8e2a6415f4b0.png)

![image](https://user-images.githubusercontent.com/1948214/72113116-75c0aa00-3337-11ea-9fe0-c2fa79e866d6.png)

5. Filesystem query storage directory is empty.

**Expected behavior**
Second response from server should include hash and `"persisted": true`.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Version 10.3.4

**Additional context**
`"apollo-client": "^2.6.8"`

**Comment by michaelstaib** [comment] 2020-01-10 07:56
You have to switch the the hash format for Apollo.

**Comment by michaelstaib** [comment] 2020-01-10 07:57
AddSha256DocumentHashProvider Has overloads. By default we use base64 and Apollo uses hex. Just pass in the enum set to hex. I am on my phone otherwise I would have pasted some code 😅

**Comment by michaelstaib** [comment] 2020-01-10 08:42
`AddSha256DocumentHashProvider(HashFormat.Hex)`

**Comment by jchapman127** [comment] 2020-01-10 17:01
@michaelstaib Ah okay, thanks! It might be worth adding that to the docs, as although I saw that overload I didn't really have any indication that my issue was due to `HashFormat`. Thanks again :)

**Comment by michaelstaib** [comment] 2020-01-14 16:44
Did you get it working or do you still have an issue here?

**Comment by jchapman127** [comment] 2020-01-14 20:52
The APQ pipeline now "works" and I can make queries, but the persisted queries are not being stored to the file system as expected.

**Comment by michaelstaib** [comment] 2020-01-14 22:11
That is strange. Can you create a little repro? Then I will look into it.

**Comment by jchapman127** [comment] 2020-01-15 20:46
I have created one [here](https://github.com/jchapman127/graphql-test), should have everything you need.

**Comment by michaelstaib** [comment] 2020-01-15 22:18
Awesome... I will look at this tomorrow morning ...

**Comment by glen-84** [comment] 2024-06-06 14:53
Closing, for lack of a minimal reproduction.

**Closed by glen-84** 2024-06-06 14:53 UTC
Labels: 🔍 investigate, 🌶️ hot chocolate, Area: Persisted Queries
