### ISSUE TITLE
[Regression] 13.x breaks schemas; AddType is no longer is respected by auto-generated FilterInputType objects

### ISSUE THREAD

**Issue by zaneclaes** [ChilliCream/graphql-platform#5923] opened 2023-03-05 01:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

As of HotChocolate 13, schemas which previously worked correctly no longer generate valid schemas because HC no longer applies the type settings to input objects.

### Steps to reproduce

1. Apply `AddType<UnsignedIntType>()` to the schema
2. Create a data model `MyData` with a `uint` property `Value`
3. Accept the data model as an argument into a GraphQL function

HotChocolate schema generation will now fail:
```
The type of the member Value of the declaring type MyData is unknown
 (HotChocolate.Data.Filters.FilterInputType<MyData>)
```

Notice that HC points the finger at the `FilterInputType` as the culprit, rather than `MyData` itself. The output object is fine; only the input object does not work.

### Additional Context?

It's simple enough to fix this by creating a custom `FilterInputType`, but that needs to be done for every single object... for me, this would take days, and add thousands of lines of unnecessary code.

### Version

13.0.5

**Comment by PascalSenn** [comment] 2023-03-05 01:17
I do not follow.
What is the expected behaviour? Do you want to filter on MyData.Value?  Is MyData a struct?

**Comment by zaneclaes** [comment] 2023-03-05 01:18
@PascalSenn the expected behavior is that, when I use the code `AddType<UnsignedIntType>()` and define a model with a `uint` value, HotChocolate does not crash.

**Comment by zaneclaes** [comment] 2023-03-05 01:24
- No, `MyData` is not a struct (it's an object).
- Yes, I want to filter on `Value`.

```
public class MyData {
  public uint Value { get; set; }
}
```

And
```
.AddType<UnsignedIntType>()
```

and
```
public class MyQuery {
  public MyData GetData(MyData args) => args;
}
```


Prior to version 13, I could do so without problem. 
Now, the schema will not even generate, as the `FilterInputType<MyData>` which is generated by HotChocolate exhibits the error from the original post.

**Comment by zaneclaes** [comment] 2023-03-05 01:29
FWIW, this fixes the schema, but does not work of course because I need to filter:

```
public class MyDataInputType : FilterInputType<MyData> {
  protected override void Configure(IFilterInputTypeDescriptor<MyData> descriptor) {
    base.Configure(descriptor);
    descriptor.Field(d => d.Value).Ignore();
  }
}
```

This does NOT fix the schema:

```
    descriptor.Field(d => d.Value).Type<UnsignedIntType>();
```

So there appears to be no way to tell a `FilterInputType` to accept a `uint` value any more...?

**Comment by glen-84** [comment] 2023-03-05 09:24
Might be a duplicate of #5448.

**Comment by PascalSenn** [comment] 2023-03-05 11:35
@glen-84  this is correct:
This is the relevant comment
https://github.com/ChilliCream/graphql-platform/issues/5448#issuecomment-1415966688

and the relevant documentation section is here:
https://chillicream.com/docs/hotchocolate/v13/fetching-data/filtering

if you like to opt for the old behaviour you can also do this:
```
    .AddFiltering(compatabilityMode: true);
```

**Closed** 2023-03-06 11:18 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, Area: Data
