### ISSUE TITLE
Random Null Reference on ResolverTask.Selection

### ISSUE THREAD

**Issue by czb182** [ChilliCream/graphql-platform#5711] opened 2023-01-23 17:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have an non public application with fairly high load, ~50 million graphql request per day.  It was using an older version, 11.1.0 and experience random null reference exceptions inside hotchocolate code.  I have updated to latest 12.16.0 and still see issue, although it seems less.

Basically I have some code to get the field names needed in SQL query.  I use an IResolverContext to check type. So basically checking IResolverContext.Field.Type.NamedType() is ObjectType, but HotChoclate ResolverTask._selection is null, so getter throws object reference not found exception.

Object reference not set to an instance of an object
HotChocolate.Execution.Processing.MiddlewareContext.get_Field

We have a small set of maybe 50 unique queries that get executed, which just couple variables changing, and the error pops up randomly.  I'm looking through ResolverTaskFactory and seeing where things get initialized, but don't know enough about internals to debug very well.

Curious if anyone else has seen issue like this.  Not sure if this is some rare race condition or maybe something going wrong earlier in pipeline and just surfacing here.

### Steps to reproduce

1. 

### Version

12.16.0

**Comment by michaelstaib** [comment] 2023-01-23 23:21
Are you using the `ResolverContext`outside of a resolver?

**Comment by michaelstaib** [comment] 2023-01-23 23:21
Also, do you have a stacktrace?

**Comment by czb182** [comment] 2023-01-24 03:20
I have my query, where I pass the IResolverContext from Resolve(...)

pseudocode

```
MyQuery : ObjectType<MyQueryView>
{
  protected override void Configure(IObjectTypeDescriptor<MyQueryView> descriptor) 
  {
    descriptor.Field(t => t.Items)
    ....
    .Resolve(async resolverContext =>
                    {
                        var dataSource = ctx.Service<IData<MyItemView>>();
                        return await dataSource.Process(resolverContext, "Id");
                    });
  }
}
```



```[
    {
        "assembly": "HotChocolate.Execution, Version=12.16.0.0, Culture=neutral, PublicKeyToken=null",
        "method": "HotChocolate.Execution.Processing.MiddlewareContext.get_Field",
        "level": 0,
        "line": 0
    },
       {
        "assembly": "GreenDonut, Version=12.16.0.0, Culture=neutral, PublicKeyToken=null",
        "method": "GreenDonut.GroupedDataLoader`2+<FetchAsync>d__1.MoveNext",
        "level": 17,
        "line": 0
    },
    {
        "assembly": "GreenDonut, Version=12.16.0.0, Culture=neutral, PublicKeyToken=null",
        "method": "GreenDonut.DataLoaderBase`2+<>c__DisplayClass21_0+<<DispatchBatchAsync>g__StartDispatchingAsync|0>d.MoveNext",
        "level": 21,
        "line": 0
    },
    {
        "assembly": "HotChocolate.Types, Version=12.16.0.0, Culture=neutral, PublicKeyToken=null",
        "method": "HotChocolate.Types.ResolverObjectFieldDescriptorExtensions+<>c__DisplayClass3_0`1+<<Resolver>b__0>d.MoveNext",
        "level": 25,
        "line": 0
    },
    {
        "assembly": "HotChocolate.Types, Version=12.16.0.0, Culture=neutral, PublicKeyToken=null",
        "method": "HotChocolate.Types.Helpers.FieldMiddlewareCompiler+<>c__DisplayClass9_0+<<CreateResolverMiddleware>b__0>d.MoveNext",
        "level": 29,
        "line": 0
    },
    {
        "assembly": "HotChocolate.Execution, Version=12.16.0.0, Culture=neutral, PublicKeyToken=null",
        "method": "HotChocolate.Execution.Processing.Tasks.ResolverTask+<ExecuteResolverPipelineAsync>d__58.MoveNext",
        "level": 33,
        "line": 0
    },
    {
        "assembly": "HotChocolate.Execution, Version=12.16.0.0, Culture=neutral, PublicKeyToken=null",
        "method": "HotChocolate.Execution.Processing.Tasks.ResolverTask+<TryExecuteAsync>d__57.MoveNext",
        "level": 37,
        "line": 0
    }
]```

**Comment by czb182** [comment] 2023-01-27 14:28
Any other information I can provide that will help?

**Comment by michaelstaib** [comment] 2023-01-30 22:51
What is `return await dataSource.Process(resolverContext, "Id");` doing with the context? The context cannot be passed of since its a rented object. It will be cleared the moment the `.Resolve(` delegate is done.

**Comment by czb182** [comment] 2023-01-31 14:56
Using context for couple things, access grabbing some data from ScopedContextData or ContextData, ReportError, checking Selection for type, basically all for building and executing query with appropriate fields and where clauses.

I don't where we are holding onto context anywhere, all executed within scope of .Resolve delegate.  All async context are awaited properly.

**Comment by czb182** [comment] 2023-02-03 19:44
Are these resolver task delegates executed in batches?  I hadn't noticed before, but i see aggregate exceptions with same error repeated 1 or more times.  Is same context passed to each task, or each get own context?

**Comment by czb182** [comment] 2023-02-04 13:07
@michaelstaib found something interesting.  I put null check on resolverContext.Selection first thing inside Process method and its already null, so looks like its being passed in that way.

MyQuery : ObjectType<MyQueryView>
{
  protected override void Configure(IObjectTypeDescriptor<MyQueryView> descriptor) 
  {
    descriptor.Field(t => t.Items)
    ....
    .Resolve(async resolverContext =>
                    {
                        var dataSource = ctx.Service<IData<MyItemView>>();
                        return await dataSource.Process(resolverContext, "Id");//null check on resolver.Context first thing inside method fails
                    });
  }
}

**Comment by michaelstaib** [comment] 2023-02-08 17:33
If you want us to help you will need to create a small repro and attach it to this issue.

**Comment by michaelstaib** [comment] 2023-02-08 17:36
> Are these resolver task delegates executed in batches? I hadn't noticed before, but i see aggregate exceptions with same error repeated 1 or more times. Is same context passed to each task, or each get own context?

tasks are executed in parallel ... every task has its own context.

**Comment by LaoR-UA** [comment] 2023-02-10 15:14
> every task has its own context.

Yes, but as far as I dived into it, I can say that each task's context is being initialized from the operation's context. I assume there may be an issue with disposing of the operation context while resolver tasks are still running.
Unfortunately, this exception is intermittent so there is no stable way to reproduce it.

**Comment by michaelstaib** [comment] 2023-02-10 17:14
We have changed this aspect in 13 ... when an operation context gets into an error state (Operation Cancellation) it will be abandoned and no longer recovered and cleaned.

Did you test it with HC 13.0.2?

**Comment by czb182** [comment] 2023-02-10 19:26
No, I think 13 is too major of a change for us to push so soon.

Now I'm wondering if should add check for cancellationtoken for each delegate, to give a more appropriate error message

descriptor.Resolve(async resolverContext =>
{
  resolverContext.RequestAborted.ThrowIfCancellationRequested();--new
  var dataSource = resolverContext .Service<IData>();
  return await dataSource.Process(resolverContext, "Id");//null check on resolver.Context first thing inside method fails
});
}

**Comment by michaelstaib** [comment] 2023-02-10 20:38
We probably can backport the fix ... it is not so big.

**Comment by czb182** [comment] 2023-02-28 20:13
I see 12.18.0 is on nuget.  Does this contain any backported fix?  Maybe we can help backport fix if pointed in right direction?

**Comment by michaelstaib** [comment] 2023-03-02 00:19
no does not yet

**Comment by LaoR-UA** [comment] 2023-03-08 16:50
We have setup like that and today we started logging the query that was sent in the request. 
Defined view and query like that:
```
public class MyQueryView: IGraphQLModel
{
        public IList<UserView> Users { get; set; } = new List<UserView>();
        public IList<RoomView> Rooms { get; set; } = new List<RoomView>();
} 

 public class MyQuery : ObjectType<MyQueryView>
 {       
        protected override void Configure(IObjectTypeDescriptor<MyQueryView> descriptor)
        {
            descriptor.Field(t => t.Users)
                .Type<ListType<UserType>>()
                .UseFiltering()
                .AddPaging()
                .Resolve(
                    async ctx =>
                    {
                        var dataSource = ctx.Service<ISQLDataSource<MyQueryView>>();                        

                        return await dataSource.Process(ctx);
                    });
         }
}
```
Defined data source:
```
public class GraphQLToSQLDataSource<TToNode> : ISQLDataSource<TToNode>
        where TToNode : IGraphQLModel
{
        // some code omitted for brevity
        public async Task<IEnumerable<TToNode>> Process(IResolverContext ctx)
        {
              if (ctx == null)
              {
                  throw new ArgumentNullException(nameof(ctx));
              }

              var query = StartQuery();
              HandleFields(ctx, query);

              return await ExecuteQueryAsync<T>(query, ctx);
        }

        protected virtual async Task<IEnumerable<T>> ExecuteQueryAsync<T>(Query query, IResolverContext context)
        {
            var compiled = queryFactory.Compiler.Compile(query);
            string sql = compiled.Sql;

            logger.LogDebug(sql);

            var command = new CommandDefinition(sql,
                compiled.NamedBindings,
                commandTimeout: queryFactory.QueryTimeout,
                cancellationToken: context.RequestAborted);

            IEnumerable<T> result = await ExecuteQueryAsync<T>(command, context);
            IList<T> resultData = result.ToList();

            var graphQuery = context?.Document?.ToString(); // <-- FAILS HERE
            LogAll(context, graphQuery, sql, resultData);

            return resultData;
        }
}
```
And we are getting NRE when trying to access the Document from context:
{"message":"Object reference not set to an instance of an object.",
"assembly":"HotChocolate.Execution, Version=12.16.0.0",
"method":"HotChocolate.Execution.Processing.MiddlewareContext.get_Document",
"level":0,
"line":0}

So, everything was executed and after that logging failed. If I look at the Document property implementation  - it is again utilizing operation context inside:
```
internal partial class MiddlewareContext
{
        public DocumentNode Document => _operationContext.Operation.Document;
}
```
Looks like it just confirms the issue with operation context disposal.

**Comment by michaelstaib** [comment] 2023-03-08 20:47
If you can... upgrade.

**Comment by LaoR-UA** [comment] 2023-04-04 16:01
Upgraded to 13.0.5 - still getting random NREs or 'ctx .Selection' is null at the beginning of the execution.
``` CSharp
public async Task<IEnumerable<TToNode>> Process(IResolverContext ctx)
        {
              if (ctx == null)
              {
                  throw new ArgumentNullException(nameof(ctx));
              }

              if (ctx.Selection == null)
              {
                  throw new ArgumentNullException(nameof(ctx), "Selection is null"); // it is being thrown
              }

              var query = StartQuery();
              HandleFields(ctx, query);

              return await ExecuteQueryAsync<T>(query, ctx);
        }
```
It has a high chance to be thrown when around 10 people are spamming requests to the GraphQL endpoint from the browser to fetch data.

**Comment by michaelstaib** [comment] 2023-04-12 14:19
Upgrade to 13?

**Comment by michaelstaib** [comment] 2023-04-12 14:21
We need a Repro project, can anybody create one?

**Comment by michaelstaib** [comment] 2023-04-12 16:32
@LaoR-UA is the logging code running after middleware is completed? I mean is it spawned off?

**Comment by czb182** [comment] 2023-04-14 01:42
> @LaoR-UA is the logging code running after middleware is completed? I mean is it spawned off?

not sure I follow but we are just leveraging ILogger interface.  Our main sink is Application Insights.

**Comment by michaelstaib** [comment] 2023-04-25 13:17
@czb182 can you create a minimal repro since we do not have this issue anywhere and cannot reproduce it in any code so far.

**Comment by michaelstaib** [comment] 2023-04-25 13:20
The issue will be closed if there is no repro for this as we invested quite some time into this and could not find this. If we get a repro this week we will look into it in the 13.1 cycle.

**Comment by michaelstaib** [comment] 2023-05-01 10:34
Closing this issue as no reproduction was provided.

**Closed** 2023-05-01 10:34 UTC
Labels: 🌶️ hot chocolate, needs-repro
