### ISSUE TITLE
Abbility to extract filters when you use [UseFiltering]

### ISSUE THREAD

**Issue by everscope** [ChilliCream/graphql-platform#6700] opened 2023-11-15 10:39 UTC
### Product

Hot Chocolate

### Is your feature request related to a problem?

I have class with a few fields
```csharp
class User
{
    public Guid Id { get; set; }
    public DateTime TimeStamp1 { get; set; }
    public DateTime TimeStamp2 { get; set; }
    public string SomeData { get; set; }
}
```

And I have following query
```csharp
  [Authorize]
  [UseFiltering]
  [UseSorting]
  public Task<IQueryable<ViewReadModel>?> GetViewsAsync(
      [Service] IUserService userService,
  ) => userService.GetUsers();
```

I have to query users using IUserService

```csharp
public class UserService : IUserService
{
    public async Task<IQueryable<User>?> GetUsers(List<Guid>? ids = null, DateTime? timeStamp1 = null, ..other optional parameters..)
    {
         some logic for querying data 
    }
}
```

IUserService returns already queried data (from another remote service for example), so if I want to query users by Id, I will have to query all of them to my service and then filter them by Id. This can be challenging, if users count is a thousands. 

### The solution you'd like

I would like to have a way to extract filters from query to pass them to custom method

For example if I have 
```graphql
user(where: { 
    id: { 
      in: [..some ids..]
    },
    timestamp: {
      gt: ..some value..
    }
  }) {
   ..user fields..
  }
```

I would like to have some way of knowing what filters where applied by user, so I can call my method as `GetUsers(<list of ids from query>, <timestamp from query>)`
As for now I think it might be possible with ObjectFieldDescriptorAttribute attribute, when you can get all filtering parameters as strings and do whatever you need, but is it possible to access filtering in another, simpler and more convenient way?

**Comment by glen-84** [comment] 2023-11-15 11:09
Duplicate of #6676.

**Closed** 2023-11-15 21:10 UTC
Labels: 🎉 enhancement
