### ISSUE TITLE
Handling of ValueTypes for Filtering

### ISSUE THREAD

**Issue by cimnine** [ChilliCream/graphql-platform#5682] opened 2023-01-13 14:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

HotChocolate fails to build the schema if filtering is defined for a [C# Value Type](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-types).

```cs
public record struct ExampleValueType(
    string Foo,
    string Bar
);

public class ExampleQueryRoot
{
    [UseFiltering]
    public IEnumerable<ExampleValueType> ValueTypes(
        [Service] ExampleRepository r)
        => r.Get();
}
```

### Steps to reproduce

Run https://gist.github.com/cimnine/7245cfc7d45796dff238c6ee50217d32 and request the schema.

### Relevant log output

```shell
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.
      
      1. For more details look at the `Errors` property.
      
      1. The type of the member ExampleValueType of the declaring type  is unknown
       (HotChocolate.Types.ObjectType<Caotina.ExampleQueryRoot>)
      
         at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(String schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(String schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass20_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Additional Context?

I think the problem is here:

https://github.com/ChilliCream/hotchocolate/blob/a159b2804945fb7cc899a222563498e87eecb1f3/src/HotChocolate/Data/src/Data/Filters/Convention/FilterConvention.cs#L307-L341

The following lines should be extended and include a check for [`IsValueType`](https://learn.microsoft.com/en-us/dotnet/api/system.type.isvaluetype?view=net-7.0):

```cs
        if (runtimeType.Type.IsClass ||
            runtimeType.Type.IsInterface)
        {
            type = typeof(FilterInputType<>).MakeGenericType(runtimeType.Source);
            return true;
        }
```

### Version

13.0.0-preview.96

**Comment by glen-84** [comment] 2023-01-16 15:27
@PascalSenn Probably also a duplicate of #4467.

**Comment by michaelstaib** [comment] 2023-01-18 10:56
You can do a PR on this of you like to.

**Comment by PascalSenn** [comment] 2023-02-03 14:40
This issue will be resolver in 13: #5760

**Closed** 2023-02-05 18:19 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, Area: Data
