### ISSUE TITLE
Init fails with BadRequest when run against Hygraph (GraphCMS) endpoint

### ISSUE THREAD

**Issue by dirkil** [ChilliCream/graphql-platform#6628] opened 2023-10-25 09:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

Hi there, I am brandnew to StrawberryShake and I am trying to get my first project to work. Unfortunately, I am struggeling with the init process. I setup a backend in Hygraph (formerly known as GraphCMS) and installed the StrawberryShake tools. Now I want to issue the init command (dotnet dotnet-graphql init <url to graphql>) but I receive a Bad Request (400) response: "error HTTP_ERROR: Response status code does not indicate success: 400 (Bad Request)."

Hygraph offers multiple endpoints: ContentAPI, High Performance Content API, Asset Upload API, Management API). What I need is the ContentAPI and the Asset Upload API. When I run the init command on either of these I am getting the above result. When I run the init command with the Management API endpoint, it works.

I contacted Hygraph support and they checked their logs and saw the issued query (see steps to reproduce) and this query works. I also entered this query directly in their GraphQL playground and I got a valid result.

It looks to me as if the processing of the response leads to the error. I can provide you with the endpoint in a private message if that helps you analyze the problem.

I hope you can help to solve this problem.

### Steps to reproduce

Run `dotnet dotnet-graphql init <url to graphql>` and you'll get the Bad Request.

I can provide you with the endpoint URL in a private message.

### Relevant log output

```shell
error HTTP_ERROR: Response status code does not indicate success: 400 (Bad Request).
```

### Additional Context?

This is the query that the Hygraph support provided me with. It was issued by the init command.

```graphql
query IntrospectionQuery {
  __schema {
    queryType {
      name
    }
    mutationType {
      name
    }
    types {
      ...FullType
    }
    directives {
      name
      description
      locations
      args {
        ...InputValue
      }
    }
  }
}
fragment FullType on __Type {
  kind
  name
  description
  fields(includeDeprecated: true) {
    name
    description
    args {
      ...InputValue
    }
    type {
      ...TypeRef
    }
    isDeprecated
    deprecationReason
  }
  inputFields {
    ...InputValue
  }
  interfaces {
    ...TypeRef
  }
  enumValues(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
  }
  possibleTypes {
    ...TypeRef
  }
}
fragment InputValue on __InputValue {
  name
  description
  type {
    ...TypeRef
  }
  defaultValue
}
fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
}
```

### Version

13.5.1

**Comment by tobias-tengler** [comment] 2023-10-25 09:32
Is there maybe an AccessToken or something similar being sent with the query through the playground? 
The HTTP status code indicates that the request reached and was rejected at the server, so it's probably not an error caused by processing the response.

If you can get a hold of the schema of your server some other way, you can also init Strawberry Shake with that as a workaround for now:

```bash
dotnet graphql init -f ./path/to/schema.graphql
```

**Comment by dirkil** [comment] 2023-10-25 12:11
I issued the introspection query through the playground to receive the schema information and save that to a file. Then I followed your recommendation and issued the init command with "-f ./path/to/schema.graphql". That seemed to have worked.

I added a query by creating a Query1.graphql file and built the solution. Now I am getting these errors:

```
0>------- Started building project: StrawberryShakeDemo
dotnet --version
dotnet "C:\Users\Dirk\.nuget\packages\strawberryshake.server\13.5.1\build\..\tools\net7\dotnet-graphql.dll" generate "C:\tmp\StrawberryShakeDemo\StrawberryShakeDemo" -o "C:\tmp\StrawberryShakeDemo\StrawberryShakeDemo\obj\Debug\net7.0\berry" -n StrawberryShakeDemo -a md5 -t
Generate C# Clients started.
Generate StrawberryShakeDemo started.
Generate StrawberryShakeDemo completed in 28 ms
0>EXEC(2,1): Error SS0001 : Expected a `Name`-token, but found a `String`-token.
0>EXEC(2,1): Error SS0001 : Expected a `Name`-token, but found a `String`-token.
0>StrawberryShake.Server.targets(79,5): Error MSB3073 : Der Befehl "dotnet "C:\Users\Dirk\.nuget\packages\strawberryshake.server\13.5.1\build\..\tools\net7\dotnet-graphql.dll" generate "C:\tmp\StrawberryShakeDemo\StrawberryShakeDemo" -o "C:\tmp\StrawberryShakeDemo\StrawberryShakeDemo\obj\Debug\net7.0\berry" -n StrawberryShakeDemo -a md5 -t" wurde mit dem Code 1 beendet.
0>------- Finished building project: StrawberryShakeDemo. Succeeded: False. Errors: 3. Warnings: 0
Build completed in 00:00:01.526
```

Any ideas what is going wrong?

**Comment by dirkil** [comment] 2023-10-25 12:36
I also got more feedback from the Hygraph people. I re-issued the init command and now they say that the query is incorrect. They issued query was:
```
query IntrospectionQuery {
schema: __schema {
queryType {
name
}
mutationType {
name
}
types {
...FullType
}
directives {
name
description
args {
...InputValue
}
onField
onFragment
onOperation
}
}
}
fragment FullType on __Type {
kind
name
description
fields(includeDeprecated: true) {
name
description
args {
...InputValue
}
type {
...TypeRef
}
isDeprecated
deprecationReason
}
inputFields {
...InputValue
}
interfaces {
...TypeRef
}
enumValues(includeDeprecated: true) {
name
description
isDeprecated
deprecationReason
}
possibleTypes {
...TypeRef
}
}
fragment InputValue on __InputValue {
name
description
type {
...TypeRef
}
defaultValue
}
fragment TypeRef on __Type {
kind
name
ofType {
kind
name
ofType {
kind
name
ofType {
kind
name
ofType {
kind
name
ofType {
kind
name
}
}
}
}
}
}
```

The error message that lead to the 400 Bad Request was:
```
{
"message": "[line: 1] field 'onField' is not defined in '__Directive'"
}
```

This is in this part of the query:
```
}
onField
onFragment
onOperation
}
}
```

**Comment by michaelstaib** [comment] 2023-10-25 22:35
Its not incorrect but for very old GraphQL servers. locations was introduced later in the GraphQL spec cycle. 

However,

try out 13.6.0-rc.0 which has a new introspection tool which should detect schema capabilities better. I close this issue as I am pretty sure it works with the new version. If it does not work reopen it with a comment.

**Closed** 2023-10-25 22:36 UTC
Labels: 🐛 bug, 🌶️ strawberry shake
