### ISSUE TITLE
Subscriptions topic stalls after some time.

### ISSUE THREAD

**Issue by DownGoat** [ChilliCream/graphql-platform#5877] opened 2023-02-21 15:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Subscription topic randomly stops working after some time. The client is still subscribed and ping/pongs are still being sent, and new messages arrive for some topics except for the failed one. It's not limited to a specific topic, sometimes _topicA_ fails, another time it's _topicB_, but eventually they all fail.

I have made a minimal solution that can be used to reproduce the issue, you can find it in this repo: https://github.com/DownGoat/HotChocolate13SubIssue

It has a single query that has properties that takes some time to resolve (simulating dataloaders, and slow db calls), and a single subscription that returns some random data. This is very similar to our setup for our project where a controller endpoint is being sent data every 5 seconds that it pushes to the topic that usually stalls first. It is the topic that has the most subscribers, and the only one that frequently sends new messages. 

I have tested the same solution with version 12.17.0, and I have not managed to reproduce the issue. We first noticed it after upgrading to version 13.

### Steps to reproduce

1. Start the following subscription
`subscription VesselPositions {
  listVessels {
    timeStamp
    int1
    int2
    int3
  }
}`
2. Send data to the topic by sending a GET request to `https://localhost:5001/WeatherForecast`. This endpoint sends a list of three entities with random data for the _intN_ fields and the current time. I use postman to repeat this request forever with a 10ms delay between each request.
3. Start and stop the subscription in BCP, after some tries the subscription stalls, and you wont be getting any new data. If this is taking a lot of time, try opening a new tab in BCP where you run the following query, while it resolves continue starting and stopping the subscription. `query WatchingPaintDry {
  slowEntity {
    prop1
    prop2
    prop3
    prop4
  }
}`

### Version

13.x.x

**Comment by nikolai-mb** [comment] 2023-02-21 16:28
We are having the same problem. After spending quite a lot of time debugging this in the HotChocolate libraries, we managed to narrow down the issue to the HotChocolate.Subscriptions.TopicShard<T> class.

As far as we can tell:
A new channel is added to the _outgoing list in the topic chard when a subscription is created.
When removing the subscription (clicking the stop / cancel button in BCP) the socket is stopped in the browser, but the channel is never removed from the list mentioned above in hot chocolate.

When reproducing we see the following:
The topic itself has a outbound channel with a default buffer of 64 messages.
Each subscription get's its own channel as outgoing buffer.
In order for the topic to "complete" a outgoing message, each subscriber needs to receive their copy.
But because closing subscriptions never completes / removes the associated channel, the _outgoing list in the TopicShard grows by one and is never reduced again.

This in turn blocks the incomming queue which reaches it's capacity of 64 items and is never removed.

We have reproduced this with BOTH graphql-ws protocols and graphql-transport-ws

**Comment by michaelstaib** [comment] 2023-02-21 17:27
I have validated this issue, we are working on a fix.

**Comment by Sibusten** [comment] 2023-03-07 15:02
Michael posted this workaround in the Slack for in-memory, which seems to work for me:
```cs
builder.Services.AddGraphQLServer()
    .AddInMemorySubscriptions(new SubscriptionOptions
    {
        TopicBufferFullMode = TopicBufferFullMode.DropOldest
    });
```

**Comment by michaelstaib** [comment] 2023-03-10 16:51
We did not forget about this issue. We will first tackle authorization issue people are facing with 13.1 and after this focus on subscriptions. This will be fixed towards the end of march as its complicated... we know what the issue is and also how to fix it, but it takes some time.

**Comment by michaelstaib** [comment] 2023-04-27 09:45
This is now fixed

**Closed** 2023-04-27 09:45 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, Area: Subscriptions, repro-validated
