### ISSUE TITLE
Support optional projection for calculated properties

### ISSUE THREAD

**Issue by th-fulcrum** [ChilliCream/graphql-platform#4981] opened 2022-04-19 16:21 UTC
### Is your feature request related to a problem?

Currently, if you have a projected property the only way to tell hot chocolate to project the required fields is to use `IsProjected(true)` which will always include the fields. This is unnecessary as a calculated field isn't necessarily always included. 

### The solution you'd like

I'd like there to be something like a `RequiredProjections` attribute which you could add to calculated fields. My imaginary syntax would look like: 

```
[RequiredProjections(Person.FirstName, Person.LastName)]
public string FullName => x.FirstName + x.LastName
```

Then, hot chocolate would be able to know, if FullName is included in the query, project FirstName and LastName.

### Product

Hot Chocolate

**Comment by glen-84** [comment] 2022-09-02 18:50
Duplicate of #2575 (?).

**Comment by glen-84** [comment] 2023-06-13 18:09
Closing as a duplicate of https://github.com/ChilliCream/graphql-platform/issues/2575.

**Closed by glen-84** 2023-06-13 18:09 UTC
Labels: 🎉 enhancement, 🌶️ hot chocolate, Area: Data, Area: Projections
