### ISSUE TITLE
Filter extension method on IQueryable<T> not working

### ISSUE THREAD

**Issue by hnazari13701371** [ChilliCream/graphql-platform#5126] opened 2022-06-06 11:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when i use Filter extension method, this method not working unless i expilictly use below code on before resolve middleware:

                     context.LocalContextData = context.LocalContextData.SetItem(QueryableFilterProvider.SkipFilteringKey
                        , false);

### Steps to reproduce

```
public class QueryType : ObjectType<Query>
    {
        protected override void Configure(IObjectTypeDescriptor<Query> descriptor)
        {

            descriptor.Field(f => f.Companies)
                .Authorize()
                .UseOffsetPaging()
                .UseProjection()
                .UseFiltering()
                .UseSorting()
                .Resolve(async ctx =>
                {
                         //load IQueryable<Company>
                });
}
}`

2.
`    public class CompanyType : ObjectType<Company>
    {
        protected override void Configure(IObjectTypeDescriptor<Company> descriptor)
        {
            descriptor.Field(f => f.Jobs)
                .Use(next => async context =>
                {
                    context.LocalContextData = context.LocalContextData.SetItem(QueryableFilterProvider.SkipFilteringKey
                        , false);
                    await next(context);
                })
                .UseOffsetPaging()
                .UseProjection()
                .UseFiltering()
                .UseSorting()
                .IsProjected(false)
                .Resolve(async ctx =>
                {
                    var skip = ctx.ArgumentValue<int>("skip");
                    var take = ctx.ArgumentValue<int>("take");
                     //load jobs from db
                    jobs = jobs.Filter(ctx).Sort(ctx);
                    if (skip > 0)
                        jobs = jobs.Skip(skip);
                    if (take > 0)
                        jobs = jobs.Take(take);
                    return jobs;
                });

}
}
```

### Product

Hot Chocolate

### Version

12.9.0

**Comment by PascalSenn** [comment] 2022-06-06 12:36
Is you resolver hit? 
hoe does the rexpression look like on `return jobs`?

**Comment by hnazari13701371** [comment] 2022-06-06 18:42
yes my resolver hit
for your second question consider I have got 10 records from DB and after using Filter, I still got 10 
I checked this Extension method, after the first time of filtering apply u set 
`context.LocalContextData.SetItem(QueryableFilterProvider.SkipFilteringKey
                    , true);`
  see below link:
https://github.com/ChilliCream/hotchocolate/blob/ad668d74ef12062eb2210c0714743628c1672e26/src/HotChocolate/Data/src/Data/Filters/Expressions/QueryableFilterProvider.cs

and it makes sense you prevent filtering twice
but why this field is already set to true when I never use filtering as u see in my code samples?
  


> Is you resolver hit? hoe does the rexpression look like on `return jobs`?

**Comment by PascalSenn** [comment] 2022-06-07 11:35
Possibly because it is "half projected" 
https://github.com/ChilliCream/hotchocolate/blob/8f0d403b1807b56215e188f2c90aec2bd5511bf2/src/HotChocolate/Data/src/Data/Projections/Expressions/Optimizers/QueryableFilterProjectionOptimizer.cs#L22-L30

i suppose it registers the middleware but does not respect IsProjected(false)

thanks for reporting

**Comment by michaelstaib** [comment] 2022-08-08 16:48
Can this one be closed?

**Comment by hnazari13701371** [comment] 2022-08-08 17:51
I am not sure , i think its a bug but i solve it by defining a middleware
and manually set property then filtering start working

**Comment by michaelstaib** [comment] 2024-07-01 09:40
We looked into this but without reproduction its difficult to understand what is wrong here. I am closing this for now. If you have a small repro you can reopen this issue and we gonna put it on the backlog.

**Closed by michaelstaib** 2024-07-01 09:40 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, 📌 pinned
