### ISSUE TITLE
Unsuccessful generation of GraphQL schema containing JSON scalar

### ISSUE THREAD

**Issue by steps371** [ChilliCream/graphql-platform#5904] opened 2023-03-02 11:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

Strawberry shake (v13.0.5) is unable to successfully generate a client from a downloaded schema containing JSON scalars.

When strawberry shake downloads a schema from a hot-chocolate API (v13) containing the new JSON scalars, it is unable successfully generate a client from the downloaded schema.

If the scalar declaration  is removed from the schema, the client is generated as expected

```
#removing scalar declaration fixes the issue, but don't want to do this everytime I fetch a reference schema
scalar JSON

type TypeWithJsonScalar {
         json: JSON
}
```

I'm assuming strawberry shake tries to add some scalars by default, regardless if they are detected in the schema reference or not? Ideally, only scalars defined in the reference should be added.

### Steps to reproduce

The bug has been reproduced in the following commit below

https://github.com/ChilliCream/graphql-platform/pull/5902/commits/b0b59d0f55c77af4c30f517f34604a25e367e862

### Relevant log output

```shell
An item with the same key has already been added. Key: JSON
```

### Version

13.0.5

**Comment by cliedeman** [comment] 2023-03-02 19:47
Duplicate of #5899

**Comment by glen-84** [comment] 2024-01-14 09:58
Closing as a duplicate of #5899.

**Closed by glen-84** 2024-01-14 09:58 UTC
Labels: 🐛 bug, 🌶️ strawberry shake
