### ISSUE TITLE
UseProjection on mutation with mutation conventions

### ISSUE THREAD

**Issue by Driedas** [ChilliCream/graphql-platform#5300] opened 2022-08-13 16:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

as per the hotchocolate [#general slack channel thread](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1660314283441189), we are using hot chocolate 12.7 with the following mutation (actual entity and property names are replaced)
```
mutation CreateEntity {
  createEntity (input: {
    foo: 1,
    bar: "aaa",
    childId: 5
  }){
    entity {
      id,
      foo,
      bar,
      childId,
      child {
        id,
        name
      }
    }
  }
}
```
The expected response should look like below (note that both the childId is returned and the child property itself is expanded)
```
{
  "data": {
    "createEntity": {
      "entity": {
        "id": 1234,
        "foo": 1,
        "bar": "aaa",
        "childId": 5,
        "child": {
          "id": 5,
          "name": "foobar"
        }
      }
    }
  }
}
```
The actual response however looks like this:
```
{
  "data": {
    "createEntity": {
      "entity": {
        "id": 1234,
        "foo": 1,
        "bar": "aaa",
        "childId": 5,
        "child": null
      }
    }
  }
}
```
The mutation method looks like this:
```
	[HotChocolate.Data.UseFirstOrDefault]
	public async Task<IQueryable<Entity>> CreateEntity(int foo,
                string bar,
                int childId,
                [Service] SomeService service,
                [Service] DataContext dataContext,
                CancellationToken cancellationToken = default)
	{
		int id = await service.CreateEntity(foo,
				bar,
                                childId,
				cancellationToken);

		return dataContext.Entities.Where(cd => cd.Id == id);
	}
```

We have tried to apply the UseProjection attribute as well, thinking that that may be the reason why we are not getting the expanded navigation property `child` but hotchocolate then throws the following exception:
```
"Unable to cast object of type 'System.Linq.Expressions.Expression1`1[System.Func`2[System.Object,System.Object]]' to type 'System.Linq.Expressions.Expression`1[System.Func`2[Entity,Entity]]'.",
```
```
at HotChocolate.Data.Projections.Expressions.QueryableProjectionScopeExtensions.Project[T](QueryableProjectionScope scope)
   at HotChocolate.Data.Projections.Expressions.QueryableProjectionContextExtensions.Project[T](QueryableProjectionContext context)
   at HotChocolate.Data.Projections.Expressions.QueryableProjectionProvider.<>c__5`1.<CreateApplicatorAsync>b__5_0(IResolverContext context, Object input)
   at HotChocolate.Data.Projections.Expressions.QueryableProjectionProvider.<>c__DisplayClass4_0`1.<<CreateExecutor>g__ExecuteAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Data.Projections.FirstOrDefaultMiddleware`1.InvokeAsync(IMiddlewareContext context)
   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
   at HotChocolate.Types.MutationConventionMiddleware.InvokeAsync(IMiddlewareContext context)
   at HotChocolate.Types.ErrorMiddleware.InvokeAsync(IMiddlewareContext context)
   at HotChocolate.AspNetCore.Authorization.AuthorizeMiddleware.InvokeAsync(IDirectiveContext context)
   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
```

@michaelstaib is suggesting that this may be connected to the rewriting of the schema when mutation conventions are applied...

### Steps to reproduce

1. have an entity framework core entity with a navigation property
2. create a graphql mutation (with mutation conventions applied) that exposes a method to persist an instance of this entity and return the newly created entity loaded from the data context (as IQueryable<T> with UseFirstOrDefault applied)
3. call the mutation method and request the result to return the entity with the navigation property expanded
4. hotchocolate returns the entity, however the navigation property is not expanded, it is null (as per above code snippets)

### Product

Hot Chocolate

### Version

12.7.0

**Comment by cts-tradeit** [comment] 2022-08-14 17:14
Try manually projecting:
```csharp
class Mutations {
    [UseProjection]
    public Task<Stuff> SaveStuff(StuffInput input, [Service] DataContext dataContext, IResolverContext ctx) {
        int stuffId = /* do something with input etc... */;
        return dataContext.Entities.Where(cd => cd.Id == id).Project(ctx).Single();
    }
}
```

If the issue persists, the problem is with the `IQueryable` itself. In this case it should throw in the `Project()` method.

If issue goes away, the problem was in the return type (probably unable to resolve `IQueryable`'s generic argument if hidden in `Task`).

**Comment by Driedas** [comment] 2022-08-14 19:31
hi, the exception is the same, the stacktrace is (obviously) slightly different this time:
```
   at HotChocolate.Data.Projections.Expressions.QueryableProjectionScopeExtensions.Project[T](QueryableProjectionScope scope)
   at HotChocolate.Data.Projections.Expressions.QueryableProjectionContextExtensions.Project[T](QueryableProjectionContext context)
   at HotChocolate.Data.Projections.Expressions.QueryableProjectionProvider.<>c__5`1.<CreateApplicatorAsync>b__5_0(IResolverContext context, Object input)
   at HotChocolate.Data.Projections.Expressions.QueryableProjectExtensions.ExecuteProject[T](T input, IResolverContext context, Type expectedType)
   at HotChocolate.Data.Projections.Expressions.QueryableProjectExtensions.Project[T](IQueryable`1 queryable, IResolverContext context)
   at Website.Graph.Extensions.Statements.ColumnDefinitionMutationExtensions.CreateColumnDefinition(Int32 columnArrangementId, Int32 ordinal, Nullable`1 columnId, Int32 columnFactoryId, String parameters, ColumnArrangementService service, RepositoryContext dataContext, IResolverContext resolverContext, CancellationToken cancellationToken) in C:\\Work\\Synchtank\\IRIS.Net\\Sources\\Server\\Website\\Graph\\Extensions\\Statements\\ColumnDefinitionMutationExtensions.cs:line 57
   at HotChocolate.Resolvers.Expressions.ExpressionHelper.AwaitTaskHelper[T](Task`1 task)
   at HotChocolate.Types.Helpers.FieldMiddlewareCompiler.<>c__DisplayClass9_0.<<CreateResolverMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Data.Projections.Expressions.QueryableProjectionProvider.<>c__DisplayClass4_0`1.<<CreateExecutor>g__ExecuteAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Types.MutationConventionMiddleware.InvokeAsync(IMiddlewareContext context)
   at HotChocolate.Types.ErrorMiddleware.InvokeAsync(IMiddlewareContext context)
   at HotChocolate.AspNetCore.Authorization.AuthorizeMiddleware.InvokeAsync(IDirectiveContext context)
   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
```

The response works as expected only when I remove UseProjection and manually include the child navigation property via
```
return dataContext.Entities
  .Include(x => x.Child)
  .Where(cd => cd.Id == id);
```

**Comment by cts-tradeit** [comment] 2022-08-14 20:33
This is strange, we use this in our project on 12.9.0 and it works. Can you test it against 12.9.0?

**Comment by Driedas** [comment] 2022-08-14 21:01
Same after upgrading to 12.9.0. The UseProjection attribute only works with no issues on the Query endpoint, it expands the child navigation property correctly...

**Comment by cts-tradeit** [comment] 2022-08-14 22:08
Btw did u remove UseSingleOrDefault before testing?

**Comment by Driedas** [comment] 2022-08-15 14:00
yep, only the UseProjection attribute is applied, as per your code snippet.
We can try this the other way round, do you have a working sample somewhere that I could checkout/fork and figure out where the differences are between your setup and ours?

**Comment by cts-tradeit** [comment] 2022-08-15 14:51
I made a working sample for you: https://github.com/cts-tradeit/hc-mutation-projection

```
mutation {
  changeLicensePlate(id: 1, newPlate: "TESTING PLATE 2") {
    id
    licensePlate
    owner {
      name
    }
  }
}
```
will produce
```
{
  "data": {
    "changeLicensePlate": {
      "id": 1,
      "licensePlate": "TESTING PLATE 2",
      "owner": {
        "name": "John Doe"
      }
    }
  }
}
```

**Comment by Driedas** [comment] 2022-08-15 15:01
thanks a lot, I'll give it a go...

**Comment by Driedas** [comment] 2022-08-15 18:59
have done a fork of the project and it works out of the box. However, as soon as you add mutation conventions into the mix, the same exception is back. In order to reproduce, try changing the graphql configuration to
```
builder.Services.AddGraphQLServer()
    .RegisterDbContext<TestDbContext>()
    .AddQueryType<Queries>()
    .AddMutationType<Mutations>()
    .AddMutationConventions() // line added
    .AddProjections();
```
and try calling the following mutation (amended to comply with the mutation conventions applied)
```
mutation ChangeLicensePlate {
  changeLicensePlate(input: { id: 1, newPlate: "foobar" }) {
    car {
      id
      licensePlate,
      ownerId,
      owner {
        id,
        name
      }
    }
  }
}
```
It looks like the mutation conventions break the `UseProjection` functionality... In fact, you don't even need to add the expanded `owner` property into the request, even this fails:
```
mutation ChangeLicensePlate {
  changeLicensePlate(input: { id: 1, newPlate: "foobar" }) {
    car {
      id
    }
  }
}
```

**Comment by cts-tradeit** [comment] 2022-08-16 08:28
As a workaround you may opt out from conventions on methods that require projection.

**Comment by Driedas** [comment] 2022-08-16 11:12
Unfortunately that is not an option at the moment, we've spent the previous "sprint" enabling mutation conventions and updating all of the frontend calls. Once we've stumbled upon this issue, we've recommended to the frontend team in the interim to follow mutation calls with a query for details, if the use case requires anything beyond the first level entity properties - hoping that this is just us having something misconfigured on our end...

Is this something that is going to be fixed? Something I can help with?

**Comment by Strandedpirate** [comment] 2022-09-01 02:37
I'm having the exact same issue. `AddMutationConventions(true)` in `program.cs`, and then any attempt to use a projection on a mutation throws an exception. This is not ideal, because now I have to map thousands of unnecessary LH-RH mappings for every mutation that I need a projection on.

```
[Authorize()]
[UseProjection]
[UseFirstOrDefault]
public async Task<IQueryable<UserCryptographyHistory>> UserCryptographyPinItem(
       MyDbContext dbContext,
       CancellationToken ct,
       [GlobalState(nameof(User.UserId))] int userId,
       [ID] int userCryptographyHistoryId)
{
  ...

  return dbContext.UserCryptographyHistories
      .Where(a => a.UserCryptographyHistoryId == userCryptographyHistoryId && a.UserId == userId)
      .AsQueryable(); // SQL query executes OK, but HC explodes
}
```

```
Unable to cast object of type 'System.Linq.Expressions.Expression1`1[System.Func`2[System.Object,System.Object]]' to type 'System.Linq.Expressions.Expression`1[System.Func`2[Ripple.Domain.Entities.Ripple.UserCryptographyHistory,Ripple.Domain.Entities.Ripple.UserCryptographyHistory]]
```

This works:
```
[Authorize()]
public async Task<UserCryptographyHistory> UserCryptographyPinItem(
       MyDbContext dbContext,
       CancellationToken ct,
       [GlobalState(nameof(User.UserId))] int userId,
       [ID] int userCryptographyHistoryId)
{
  ...

  return await dbContext.UserCryptographyHistories
        .Where(a => a.UserCryptographyHistoryId == userCryptographyHistoryId && a.UserId == userId)
        // this sucks, having to map LH-RH for all the things, cause I need one column from the CryptographyType table...
        .Select(a => new UserCryptographyHistory
        {
            CreatedOn = a.CreatedOn,
            CryptographyType = new CryptographyType
            {
                Name = a.CryptographyType.Name
            },
            CryptographyTypeId = a.CryptographyTypeId,
            Input = a.Input,
            IsFavorite = a.IsFavorite,
            IsPinned = a.IsPinned,
            Output = a.Output,
            User = a.User,
            UserCryptographyHistoryId = a.UserCryptographyHistoryId,
            UserId = userId,
        })
        .FirstOrDefaultAsync();
}
```

**Comment by Rlamotte** [comment] 2023-01-03 10:06
I reproduce the same behaviour which seems to be a bug due to conflict between UseProjection and UseMutationConvention.

Currently I'm forced to include manually child elements which represents a lack of performance and causes graphQL to be a bit obsolete...

A fix which give the opportunity to use MutationConvention (which seems great to make mutation sustainable) and UseProjection (which seems perfect to be able to let the client choose only variables needs) together would be appreciated.

**Comment by JordanGistLens** [comment] 2023-04-15 04:32
I've been running into this also using v13.0.5, I'm a big fan of mutation conventions but without projections it's making some of the more complex responses involving multiple nested navigation properties really hard to support. @michaelstaib is this on any roadmap or intended to be resolved in any upcoming release?


Here is another example of how I'm using them where it produces the below error.
```C#
[ExtendObjectType(OperationTypeNames.Mutation)]
public class TenantCreateMutation
{
    [UseFirstOrDefault]
    [UseProjection]
    [Error(typeof(DomainException))]
    public async Task<IQueryable<Tenant>> TenantCreate(
        [Service] ApplicationDbContext database,
        [Service] IRequestClient<TenantCreateCommand> client,
        string name,
        CancellationToken cancellation)
    {
        var command = new TenantCreateCommand { Name = name };

        Response response =
            await client.GetResponse<TenantCreateCommandResult, TenantCreateCommandRejected>(command, cancellation);
        return response switch
        {
            (_, TenantCreateCommandResult result) => database.Tenants.Where(x => x.Id == result.Id),
            (_, TenantCreateCommandRejected error) => throw new DomainException(error.ErrorCode),
            _ => throw new InvalidOperationException()
        };
    }
}
```

```
      "extensions": {
        "message": "Unable to cast object of type 'System.Linq.Expressions.Expression1`1[System.Func`2[System.Object,System.Object]]' to type 'System.Linq.Expressions.Expression`1[System.Func`2[Giantnodes.Service.Tenants.Domain.Entities.Tenant,Giantnodes.Service.Tenants.Domain.Entities.Tenant]]'.",
        "stackTrace": "   at HotChocolate.Data.Projections.Expressions.QueryableProjectionScopeExtensions.Project[T](QueryableProjectionScope scope)\r\n   at HotChocolate.Data.Projections.Expressions.QueryableProjectionContextExtensions.Project[T](QueryableProjectionContext context)\r\n   at HotChocolate.Data.Projections.Expressions.QueryableProjectionProvider.<CreateApplicator>b__7_0[TEntityType](IResolverContext context, Object input)\r\n   at HotChocolate.Data.Projections.Expressions.QueryableProjectionProvider.<>c__DisplayClass4_0`1.<<CreateExecutor>g__ExecuteAsync|1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Data.Projections.FirstOrDefaultMiddleware`1.InvokeAsync(IMiddlewareContext context)\r\n   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)\r\n   at HotChocolate.Types.MutationConventionTypeInterceptor.<>c__DisplayClass16_0.<<ApplyResultMiddleware>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Types.MutationConventionMiddleware.InvokeAsync(IMiddlewareContext context)\r\n   at HotChocolate.Types.ErrorMiddleware.InvokeAsync(IMiddlewareContext context)\r\n   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
      }
```

**Comment by Pjotrtje** [comment] 2023-05-27 12:35
FYI, when not using the "ErrorAttributes flow" but when using the "MutationResult flow" it is also broken. Thus someting like (rewrote above code in other flow):
```csharp
[ExtendObjectType(OperationTypeNames.Mutation)]
public class TenantCreateMutation
{
    [UseFirstOrDefault]
    [UseProjection]
    public async Task<IQueryable<MutationResult<Tenant, DomainError>>> TenantCreate(
        [Service] ApplicationDbContext database,
        [Service] IRequestClient<TenantCreateCommand> client,
        string name,
        CancellationToken cancellation)
    {
        var command = new TenantCreateCommand { Name = name };

        Response response =
            await client.GetResponse<TenantCreateCommandResult, TenantCreateCommandRejected>(command, cancellation);
        return response switch
        {
            (_, TenantCreateCommandResult result) => database.Tenants.Where(x => x.Id == result.Id),
            (_, TenantCreateCommandRejected error) => new DomainError(error.ErrorCode),
            _ => throw new InvalidOperationException()
        };
    }
}

```
also fails. 

I think "Stage 6a Errors" are the way to go, but to make it usefull it should be able to work with Projections... Best would be that code as above would work. But a temp workable workaround would also be very valuable I guess. Something like the above mentioned 
```return await dbContext.Set<Car>().Where(c => c.Id == id).Project(ctx).SingleAsync();```
Something like
```return await dbContext.Set<Car>().Where(c => c.Id == id).ProjectOkResult(ctx).SingleAsync();``` 
(which only uses the "non-errors" part of the projection)

**Comment by hahn-kev** [comment] 2023-07-27 10:13
I'm also running into this. It looks like there's [some code](https://github.com/ChilliCream/graphql-platform/blob/e60254347fa17e1e17b93ccf7d62f0f083651c14/src/HotChocolate/Data/src/Data/Projections/Extensions/ProjectionObjectFieldDescriptorExtensions.cs#L199-L206) for handling a similar issue when using Relay conventions. I'm not sure how much work it might be, but I'm considering looking into this and making a PR for it.

**Closed** 2023-08-17 07:59 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, Area: Data, Area: Projections

**Comment by Pjotrtje** [comment] 2023-08-29 14:57
@michaelstaib, @hahn-kev , did we expect the linked PR to also solve the issue for MutationResults + Projections? Thus something like:

```csharp
[ExtendObjectType(OperationTypeNames.Mutation)]
public class TenantCreateMutation
{
    [UseFirstOrDefault]
    [UseProjection]
    public async Task<MutationResult<IQueryable<Tenant>, DomainError>> TenantCreate(
        [..]
        CancellationToken cancellation)
    {
        [..]
    }
}
```
i.c.w. `.AddMutationConventions`

Becasue it throws "Cannot Resolve PayLoadType"; even with latest versions of HC

**Comment by hahn-kev** [comment] 2023-08-29 15:02
I didn't test that case. You should be able to just use the queryable as the return type and let the mutation convention change the type in the scheme.

**Comment by nicomoya123** [comment] 2024-03-18 20:39
@Pjotrtje did you open an issue on it ?
I am facting the same issue

**Comment by Pjotrtje** [comment] 2024-03-20 19:29
@nicomoya123 nope. So feel free to open issue. And I will give it a heart :)
