### ISSUE TITLE
Cannot mix projected and non-projected properties

### ISSUE THREAD

**Issue by atrauzzi** [ChilliCream/graphql-platform#6041] opened 2023-04-11 13:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have the following:

```csharp
    [GraphQLIgnore]
    internal IList<LockConfiguration> DomainLockConfiguration { get; init; } = new List<LockConfiguration>();

    [IsProjected(false)]
    public IList<string> LockSchemes => DomainLockConfiguration.Select((configuration) => configuration switch
    {
        PaymentLockConfiguration => "payment",
        _ => throw new("Unsupported lock scheme encountered."),
    }).ToList();
```

But whenever I include `lockSchemes` in my queries, it always comes out as an empty array and the getter is never run.

### Steps to reproduce

Create a computed property on a type to be serialized.

### Version

13

**Comment by glen-84** [comment] 2023-06-12 18:43
@PascalSenn Can this be closed as a duplicate of #2575?

**Comment by glen-84** [comment] 2024-01-17 13:49
Closing as a duplicate of #2575.

**Closed by glen-84** 2024-01-17 13:49 UTC
Labels: 🐛 bug, 🐾 duplicate, 🌶️ hot chocolate, Area: Data, Area: Projections
