### ISSUE TITLE
Scalars like UnsignedLongType with Filtering is Broken on version 13

### ISSUE THREAD

**Issue by MarcoMedrano** [ChilliCream/graphql-platform#5448] opened 2022-09-30 03:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Use ulong, uint, ushort etc.
```
public class Poco
{
    public virtual string Name { get; set; }
    public virtual ulong? Age { get; set; }
}
```
Use Filtering and common annotations for queries
```
    [UseOffsetPaging(IncludeTotalCount = true)]
    [UseProjection]
    [UseFiltering]
    [UseSorting]
    public virtual IQueryable<Poco> GetPocos()
    {
        var list = new List<Poco>{new Poco(), new Poco()};

        return list.AsQueryable();
    }
```

Add Filtering in the GraphQLServer
```
builder.Services.AddGraphQLServer()
                .AddType<UnsignedLongType>()
                .BindRuntimeType<ulong, UnsignedLongType>() // This should not be needed but I tried with and without it.
                .AddQueryType<Query>()
                .AddFiltering()
                .AddSorting()
                .AddProjections()
```

### Steps to reproduce

1. Just run a query against it or another one, not even the schema is generated,  it throws the  `The type of the member Age of the declaring type Poco is unknown (HotChocolate.Data.Filters.FilterInputType<Poco>)`

### Relevant log output

```shell
1. The type of the member Age of the declaring type Poco is unknown
       (HotChocolate.Data.Filters.FilterInputType<Poco>)
      
         at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(String schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(String schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass20_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Additional Context?

Version 12.14.0 has no such issue, but version 13.0.0-preview.XX

Here is the minimal code if you want to reproduce the bug: https://github.com/MarcoMedrano/hotchocolate-ulong-bug

### Product

Hot Chocolate

### Version

13.0.0-preview.64

**Comment by glen-84** [comment] 2023-01-16 15:23
@PascalSenn Duplicate of #5262 (which is possibly a duplicate of #4467).

**Comment by PascalSenn** [comment] 2023-02-03 14:42
So there is a bit of a history behind this issue.

In the past we were generating all input types for filtering. This lead to awful type names like Int16FilterOperationInpuType. We then decided we will just fully type them out and bind them directly to the proper type.

Therefor, when you use e.g. UnsignedInt, then you will have to create a custom filter input type for this. I updated the documentation in #5759

**Closed by PascalSenn** 2023-02-03 14:42 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, Area: Data

**Comment by MarcoMedrano** [comment] 2023-02-03 16:57
@PascalSenn, well the logical names we will have to think about are not less awful, as in your sample `UnsignedIntOperationFilterInputType`, in addition to the not intuitive extra configuration we need to code. 
I believe the autogenerated name like `Int16FilterOperationInpuType` makes it much easier the use of HotChocolate. I'd suggest generating the default configuration under the hood and letting the developer override it if he wants to.

Thanks for the documentation, I'll be able to use unsigned numbers again in the 13 version.

**Comment by PascalSenn** [comment] 2023-03-05 11:36
@MarcoMedrano  

You can opt for the old behaviour, allthough i do not recommend it for new projects:
```csharp
    .AddFiltering(compatabilityMode: true);
```
