### ISSUE TITLE
#strawberry-shake how can I reconnect websocket if somehow Server is Restarted and connection is lost 

### ISSUE THREAD

**Issue by ibnekhalid** [ChilliCream/graphql-platform#4184] opened 2021-09-03 15:07 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

**#strawberry-shake** how can I reconnect websocket if somehow Server is Restarted and connection is lost 

There should be onConnect and OnDisconnet events callbacks.

### Steps to reproduce

 **My Startup** as per documentation

`       services.AddBkClient(profile: BkClient.BkClientProfileKind.Default).ConfigureHttpClient((sp , client) =>`
`             {`
`                 var login = sp.GetService<Login>( );`
`                 _token = login.GetAccessToken( );`
`                 client.BaseAddress = new Uri(_appSettings.BkQueryUrl);`
`                 client.AddBearerToken(_token);`
`             }).ConfigureWebSocketClient((sp , client) =>`
`             {`
`                 client.Uri = new Uri(_appSettings.BkWsUrl);`
`             });`

### Product

Strawberry Shake

### Version

11.3.5

**Comment by ibnekhalid** [comment] 2021-09-04 08:39
@tobias-tengler  Do we any work around for now? To reconnect websocket and getting subscriptions live.

**Comment by jonbmul** [comment] 2021-09-08 21:14
The GraphQL.Net client exposes a WebsocketConnectionState property that can be subscribed to. This is super useful when you need to synchronize data after connectivity issues. Would be great if Strawberry Shake could offer something similar

**Comment by ibnekhalid** [comment] 2021-11-01 06:55
@horego  thanks, but for now i have implemented SignalR (with websocket connection) until the issue is not resolved. Once the issue would be resolved i would move to the #StrawberryShake Subscriptions again.

**Comment by ibnekhalid** [comment] 2021-11-01 07:00
@horego, You are observing socket connection on Client side only but i need to capture Disconnect on Server also.

**Comment by ibnekhalid** [comment] 2021-11-01 07:03
@michaelstaib, i know you people are working on other millstones also. Are you people done with this issue?

Thanks?

**Comment by CoreDX9** [comment] 2022-04-26 08:59
I have a interim solution. Look at #5006 .

**Comment by fhewitt** [comment] 2023-03-17 13:35
This issue make the whole feature of subscriptions more or less unusable, no? That's great for things that complete in a short time, but for any long lived subscriptions, an absence of automatic reconnexion / notification mechanism is really wrong. :/ Does something prevent to apply the CoreDX9 solution of completing the subscription on case of deconnection?

**Comment by michaelstaib** [comment] 2023-03-20 14:22
@fhewitt do you want to help on this? We have started work on a new underlying socket handling but any help is welcome.

**Comment by JenMQ** [comment] 2023-05-15 05:49
I am facing connection issues as well and trying to figure out how to reconnect the websocket connection. For cases when internet drops or when auth token expires, I wanted to be able to check and reconnect if the web socket connection is disrupted. I also notice that the WebSocket client's state goes on Aborted state.

I tried the The GraphQL.Net client and did not face this issues. Would be great if Strawberry Shake can have an OnError or OnDisconnected event or an observable that can subscribed to so that a proper handling can be done.

**Comment by gowthambala** [comment] 2023-07-25 15:31
> I am facing connection issues as well and trying to figure out how to reconnect the websocket connection. For cases when internet drops or when auth token expires, I wanted to be able to check and reconnect if the web socket connection is disrupted or if not successful. I also notice that the WebSocket client's state would go on Aborted state and have no clue why when how that happened.
> 
> I tried the GraphQL.Net client and did not face these issues. Would be great if Strawberry Shake can have an OnError or OnDisconnected event or an observable that can subscribed to so that a proper handling can be done.
> 
> Much better if it would reconnect automatically.

I am running into the same issue. where is able to identify a solution or a workaround?

**Comment by JenMQ** [comment] 2023-07-28 06:26
@gowthambala unfortunately, we had to postpone the usage of strawberry shake on our project due to the issue mentioned above. But now, we have to try again but looks like there are no fixes/updates made yet.

**Comment by JenMQ** [comment] 2023-07-28 06:27
> @fhewitt do you want to help on this? We have started work on a new underlying socket handling but any help is welcome.

@michaelstaib are there any updates on possible solution/workaround for the reconnection issue?

**Comment by datoon83** [comment] 2024-03-15 09:14
@JenMQ - did you get this working?

**Comment by jzabroski** [comment] 2024-07-23 14:57
@michaelstaib This also affects me. We missed a critical event. Please - At least update the documentation to note this critical defect exists, and some official workaround in the documentation. Maybe even suggest users try GraphQL.NET until a fix for this problem is available.

Will repeat and agree with @fhewitt [feedback here](https://github.com/ChilliCream/graphql-platform/issues/4184#issuecomment-1473854803):

> This issue make the whole feature of subscriptions more or less unusable

### Summary

* The workaround posted by @horego uses `StrawberryShake.Transport.WebSockets.ISocketConnectionInterceptor`.
  * Uses an observable timer to periodically poll the current StrawberryShake IWebSocketClient.IsClosed property. It's not clear to me why this code has to live inside an ISocketConnectionInterceptor.
  * @fhewitt says that "Need to add that the two workarounds I've found here seem outdated and does not work properly." but did not elaborate how they do not work properly. (I'm digging into this now. I suspect he means that IWebSocketClient.IsClosed only checks normal closures (difference between Close vs. Abort), when really this abstraction should probably check WebSocketCloseStatus is null or not, as that would likely check for failures caused by network issues like DNS changes)
  * Only one ISocketConnectionInterceptor can be assigned to an IWebSocketClient. If you're integrating with a legacy server that expects the authorization token to be passed as part of the initial payload, you will need to _also_ create a CompositeConnectionInterceptor that calls both your InitialAuthorizationPayloadConnectionInterceptor and [this DeadSocketConnectionInterceptor](https://github.com/horego/hotchocolate-graphql-examples/blob/3b17de518cf5afdc866812fe46641680fb93436f/GraphQL.ClientApp/DeadSocketConnectionInterceptor.cs#L1).
* @CoreDX9 's workaround was merged into main, but doesn't have any release tags associated with it, so it's unclear to me if it's actually in production. Additionally, [he/she notes](https://github.com/ChilliCream/graphql-platform/pull/5008#issuecomment-1110802065) "this pull request can only let the client detect the subscription that ends normally. If the socket is closed due to server crash or network error, the client cannot receive the message of completing the subscription, so this notification will not be triggered."

**Comment by michaelstaib** [comment] 2024-07-24 11:19
We have implemented the original ask of this issue which is providing hooks for connection events. #7295 

This actually was already implemented for a while and accessible through an event on the socket client. The event however was not named in a way that I think many of you would have found discoverable.

We have now introduced `OnConnectionOpened` and `OnConnectionClosed` on the `ISocketConnectionInterceptor` this aligns well with the way we do it in the server. Both events pass on the connection object on which you get direct access to the underlying websocket.

In general if you want have less abstraction then we have `HotChocolate.Transport.WebSocket` as a package... which implements the client transport without any abstraction level.

**Closed by michaelstaib** 2024-07-24 11:19 UTC
Labels: 🐛 bug, 🌶️ strawberry shake
