### ISSUE TITLE
OK status code can be returned from failed request with errors but empty data

### ISSUE THREAD

**Issue by originalplayer** [ChilliCream/graphql-platform#3842] opened 2021-06-18 13:10 UTC
I have a mutation request that causes an exception to be thrown by my resolver code. Normally, the IQueryResult object has a null Data field and a populated Errors field. The DefaultHttpResultSerializer.GetStatusCode method then returns InternalServerError for the status code which is fine. However, I have found that sometimes the Data field is also populated (for the same request, failing in exactly the same way). However, the data item that it is populated with (a ResultMap) has nothing in it. This causes the status code to be set to OK because the Data field is not null. This means that I sometimes get OK and sometimes get InternalServerError for exactly the same request failing in the same manner. 

This has proved difficult to reproduce in a reliable way, but I have some unit tests on my service that fire multiple requests in parallel at the service. At some point during these tests HotChocolate seems to get into a mode where it starts giving me the wrong status code back. If these tests are run serially then the problem doesn't happen. After being run in parallel and having seen a failure, running the tests serially will then also result in failure, 

As a side issue, the ResultMap that is present in the Data field when the problem happens seems a little odd in that the Count field returns a value of 1 but getting the enumerator returns no content because the ResultMap only returns populated entries. This may be desired behaviour but seems a little odd.

I am running on Windows 10.
I am using HotChocolate 11.3.0

Thanks.

**Comment by michaelstaib** [comment] 2021-06-18 21:35
Can you provide a repro for this?

**Comment by originalplayer** [comment] 2021-06-19 09:29
This is hard to reproduce due to the somewhat random nature of it, which I believe to be down to concurrent requests. So I'm afraid I don't currently have a stand-alone application that reproduces it. The parallel requests are a mixture of queries and mutations some of which will succeed and some of which fail as a result of exceptions being thrown from our resolvers.

**Comment by Vertigo093i** [comment] 2021-07-22 14:38
We experience the very same problem.

**Comment by anadale** [comment] 2021-12-07 16:01
I've tried to code-trace the issue and the only candidate I see is the chain `WriteData`/`WriteResultMap` in `JsonQueryResultSerializer`. It seems that the result of the execution is `IResultMap` with (probably) single value which is not initialized, so `WriteResultMap` doesn't actually output anything but empty object, and `WriteData` outputs `data` property since `data` is not `null` and has something in it. As it was said before, I'm unable to reproduce the problem locally, but that's the only way it can be if we'll trace the code. I'll try to make a PR to fix the problem.

**Comment by ChebotkovDV** [comment] 2022-01-10 13:09
This error is also reproduced in our environment. Additional information, may help in correction. On gateway, when serialized in `IExecutionResult`, an empty array is set for the `Data` field:
```
{
    "Label": null,
    "Path": null,
    "Data": [],
    "Errors": [ { "Message": ... } ],
    "Extensions": null,
    "ContextData": null,
    "HasNext": null,
    "$type": "QueryResult"
}
```
Because of what the answer looks like, with the code `200`:
```
{
  "errors": [ {  "message": ... } ],
  "data": {}
}
```
So far, we have decided in a similar way on gateway:
```
public class HttpResultSerializer : DefaultHttpResultSerializer
{
    public override ValueTask SerializeAsync(IExecutionResult result, Stream stream,
        CancellationToken cancellationToken)
    {
        if (result is IQueryResult queryResult)
        {
            if (queryResult.Data != null && queryResult.Errors != null && !queryResult.Data.Any())
            {
                return base.SerializeAsync(new QueryResult(null, queryResult.Errors), stream, cancellationToken);
            }
        }
        return base.SerializeAsync(result, stream, cancellationToken);
    }
}
```

**Comment by michaelstaib** [comment] 2022-01-10 21:45
@ChebotkovDV can you state your version

**Comment by ChebotkovDV** [comment] 2022-01-11 07:16
@michaelstaib sorry, yes - 12.4.1

**Comment by michaelstaib** [comment] 2022-01-11 08:00
Can you create a small repro?

**Comment by ChebotkovDV** [comment] 2022-01-11 09:38
No, unfortunately, this is reproduced only in our production environment, locally I have not been able to reproduce it

**Comment by michaelstaib** [comment] 2022-01-25 16:31
Does anyone implement a DiagnosticEventListener? @ChebotkovDV @anadale

**Comment by anadale** [comment] 2022-01-26 13:14
No, we does not.

**Comment by Pjotrtje** [comment] 2022-03-18 11:02
I have same problem. And I can reproduce it constantly. I do not have the time to create repo with problem; maybe later this month. But to reproduce:

1) Make GraphQL mutation whch always throws an error
2) Make console app which calls mutation single threaded -> All works perfectly all the time. Result of call:
```cs
{
  "errors": [ {  "message": ... } ],
}
```
3) Make console app which calls mutation with 12 threads -> Immidiate fail due to not null data. Result of call:
```cs
{
  "errors": [ {  "message": ... } ],
  "data": {}
}
```

The weird thing is once the empty data object is returned, even when multithreaded is stopped, the result of the call will include empty data object. So the problem is somewhere in shared state I guess?

@ChebotkovDV thanks for the HttpResultSerializer example! That workaround worked perfect.

**Comment by michaelstaib** [comment] 2023-01-30 22:24
This is fixed with version 13

**Closed by michaelstaib** 2023-01-30 22:24 UTC
Labels: 🐛 bug, 🔍 investigate, 🌶️ hot chocolate, 📌 pinned
