### ISSUE TITLE
StrawberryShake 13 emits warnings warning CS8604: Possible null reference argument for parameter 'data' in...

### ISSUE THREAD

**Issue by nightroman** [ChilliCream/graphql-platform#5869] opened 2023-02-19 19:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

StrawberryShake 13 emits warnings warning CS8604: Possible null reference argument for parameter 'data' in...

Source code: [SSv13.zip](https://github.com/ChilliCream/graphql-platform/files/10777702/SSv13.zip)

### Steps to reproduce

1. Use the attached project and change to it
2. Run `dotnet build`
3. See warnings

### Relevant log output

```
MSBuild version 17.4.1+fedecea9d for .NET
  Determining projects to restore...
  Restored C:\Users\roman.kuzmin\source\repos\bugs\HotChocolate\SSv13_230219_1910\SSv13\Nexar.Client.csproj (in 172 ms).
  Generate C# Clients started.
  Generate NexarClient started.
  Generate NexarClient completed in 903 ms
  Generate C# Clients completed in 1028 ms
C:\Users\roman.kuzmin\source\repos\bugs\HotChocolate\SSv13_230219_1910\SSv13\obj\Debug\net6.0\berry\NexarClient.Client.cs(2537,495): warning CS8604: Possible null reference argument for parameter 'data' in 'ITaskByNodeId_Node_Assignee TaskByNodeIdResultFactory.MapNonNullableITaskByNodeId_Node_Assignee(DesUserData data)'. [C:\Users\roman.kuzmin\source\repos\bugs\HotChocolate\SSv13_230219_1910\SSv13\Nexar.Client.csproj]
C:\Users\roman.kuzmin\source\repos\bugs\HotChocolate\SSv13_230219_1910\SSv13\obj\Debug\net6.0\berry\NexarClient.Client.cs(2537,557): warning CS8604: Possible null reference argument for parameter 'data' in 'ITaskByNodeId_Node_CreatedBy TaskByNodeIdResultFactory.MapNonNullableITaskByNodeId_Node_CreatedBy(DesUserData data)'. [C:\Users\roman.kuzmin\source\repos\bugs\HotChocolate\SSv13_230219_1910\SSv13\Nexar.Client.csproj]
C:\Users\roman.kuzmin\source\repos\bugs\HotChocolate\SSv13_230219_1910\SSv13\obj\Debug\net6.0\berry\NexarClient.Client.cs(2537,621): warning CS8604: Possible null reference argument for parameter 'data' in 'ITaskByNodeId_Node_ModifiedBy TaskByNodeIdResultFactory.MapNonNullableITaskByNodeId_Node_ModifiedBy(DesUserData data)'. [C:\Users\roman.kuzmin\source\repos\bugs\HotChocolate\SSv13_230219_1910\SSv13\Nexar.Client.csproj]
  Nexar.Client -> C:\Users\roman.kuzmin\source\repos\bugs\HotChocolate\SSv13_230219_1910\SSv13\bin\Debug\net6.0\Nexar.Client.dll

Build succeeded.
```

### Version

13.0.2

**Comment by nightroman** [comment] 2023-06-02 15:38
v13.2, same issue

**Comment by GKotfis** [comment] 2023-08-21 10:26
This issue is a blocker when you have a `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` on solution :(
Block me with migration to v13.

**Comment by johan-lindqvist** [comment] 2023-10-16 06:10
We're also having this issue, to get past the warnings our current workaround is to ignore the warning in the project

By adding this in the csproj-file
```
<NoWarn>8604</NoWarn>
```

**Comment by glen-84** [comment] 2023-12-27 09:23
Closing as a duplicate of #3985.

**Closed by glen-84** 2023-12-27 09:23 UTC
Labels: 🐛 bug, 🐾 duplicate, 🌶️ strawberry shake
