### ISSUE TITLE
Write errors from HotChocolate.Fusion.CommandLine to stderr instead of stdout

### ISSUE THREAD

**Issue by interad-woergoetter** [ChilliCream/graphql-platform#6575] opened 2023-10-05 08:38 UTC
### Product

Hot Chocolate

### Is your feature request related to a problem?

Detecting errors in CI/CD is a little bit difficult, because both successful and unsuccessful commands write to standard out but do not write to standard error.

### The solution you'd like

I would prefer if the fusion command line tool would write errors to standard error instead of standard out.

**Comment by PeterMedusRES** [comment] 2024-01-09 12:18
We've encountered a similar issue with `HotChocolate.AspNetCore.CommandLine` when running the `schema export` command in GitHub Actions.

The CI pipeline continues running despite the unhandled exception stack trace being written to stdout. I believe the reason for this is actually because the command is returning a zero exit code despite having failed, instead of a non-zero exit code to indicate a failure. But I also agree that using stderr for error messages would be a useful enhancement.

**Comment by interad-woergoetter** [comment] 2024-01-09 13:23
Good point. I only mentioned stderr because we are using Azure DevOps and that has a failOnStderr option.

**Comment by FelixZY** [comment] 2024-02-21 23:25
+1 for this and a bit of extra emphasis on changing the status code from zero to non-zero on error. Not all environments have a failOnStdErr option.

**Comment by dkAnBlWo** [comment] 2024-05-03 07:34
+1 to this. We are currently considering adopting Fusion for a distributed graph solution. However, we can't generate schema files for our existing services, even when everything's updated to the latest HotChocolate prerelease version.
Not having error output means we can't investigate the issue, and it seems risky to bet on this for anything business critical.

**Comment by michaelstaib** [comment] 2024-05-03 23:10
@dkAnBlWo shall we setup a call to see what the issue is you guys are having? Send us an email to: contact at chillicream.com

Closing the issue as we fixed the stderr.

**Comment by michaelstaib** [comment] 2024-05-08 20:35
@tobias-tengler can this be closed?

**Closed** 2024-05-09 05:01 UTC
Labels: 🎉 enhancement, 🌶️ hot chocolate, Area: Fusion, Next
