### ISSUE TITLE
Directive middleware on root types is not executed

### ISSUE THREAD

**Issue by wassim-k** [ChilliCream/graphql-platform#5881] opened 2023-02-22 02:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

In HC v12, when running the test below, the authorization middleware gets executed for any field under Query root type.
But in v13, the test fails as the middleware no longer gets executed. The same is true for any other middleware for custom directives on a root query type (not just authorization directive).

Can you please advise on what the issue might be?

```csharp
public class Bug
{
    [Fact]
    public async Task DirectiveMiddlewareOnRootTypeIsExecuted()
    {
        var authorizationHandlerMock = new Mock<IAuthorizationHandler>();

        var result = await new ServiceCollection()
            .AddAuthorization()
            .AddGraphQL()
            .AddAuthorizationHandler(sp => authorizationHandlerMock.Object)
            .AddQueryType<Query>(q => q
                .Authorize(ApplyPolicy.BeforeResolver))
            .ExecuteRequestAsync("{ person { name } }");

        authorizationHandlerMock
            .Verify(ah => ah.AuthorizeAsync(It.IsAny<IMiddlewareContext>(), It.IsAny<AuthorizeDirective>(), It.IsAny<CancellationToken>()), Times.Once);
    }

    public class Query
    {
        public Person GetPerson() => new() { Name = "Tester" };
    }

    public class Person
    {
        public string Name { get; set; }
    }
}
```

### Steps to reproduce

1. Run above test

### Version

13.0.0

**Comment by michaelstaib** [comment] 2023-02-27 14:56
Thats not a bug but by design.

If you put authorize directives in the execution phase on a type Hot Chocolate will ensure that all caller resolvers will be secured. Since the root type in general is not referenced by a called it will have no effect.

In this particular case use the validation phase.

What we could do is throw a schema exception in this case. However, there are some edge cases where you re-expose the query type on mutation payloads where this still could be useful.

I am closing this issue as it is not a bug.

**Closed by michaelstaib** 2023-02-27 14:56 UTC
Labels: 🐛 bug, 🌶️ hot chocolate
