### ISSUE TITLE
Loading a remote schema fails because a directive is registered twice after upgrade to 13.6.0

### ISSUE THREAD

**Issue by peterhut** [ChilliCream/graphql-platform#6637] opened 2023-10-27 07:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

With the upgrade from 13.5.1 to 13.6.0 the loading of a RemoteSchema fails with the error "The name `tag` was already registered by another type. (HotChocolate.Types.DirectiveType<HotChocolate.Types.Tag>)"

The error appears to be caused by the Tag type being registered first in
https://github.com/ChilliCream/graphql-platform/blob/4908039965009766d9c9b7ab47cfb217b9a6704d/src/HotChocolate/Core/src/Types/Configuration/TypeDiscoverer.cs#L100
And then again in:
https://github.com/ChilliCream/graphql-platform/blob/4908039965009766d9c9b7ab47cfb217b9a6704d/src/HotChocolate/Core/src/Types/Configuration/TypeDiscoverer.cs#L101

### Steps to reproduce

1. Reference HotChocolate.AspNetCore and HotChocolate.Stitching 13.6.0
2. Configure GraphQLServer by adding a RemoteSchema
```
builder.Services
    .AddGraphQLServer("abc")
    .AddInMemorySubscriptions()
    .ModifyRequestOptions(o => o.IncludeExceptionDetails = true)
    .AddRemoteSchema("xyz", ignoreRootTypes: false)
    .AddTypeExtensionsFromFile("./GraphQL/AbcStitching.graphql");
```
Where the remote schema is similar to: [cleanedupschema.graphql.txt](https://github.com/ChilliCream/graphql-platform/files/13186308/cleanedupschema.graphql.txt) (I removed some stuff I thought was unrelated, so let me know if it is no longer sufficient to reproduce the issue)
3. Start the Web Application and try loading the GraphQL schema.

### Relevant log output

```shell
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. The name `tag` was already registered by another type. (HotChocolate.Types.DirectiveType<HotChocolate.Types.Tag>)

         at HotChocolate.Configuration.TypeRegistry.Register(String typeName, RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.CompleteTypeName(RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
         at HotChocolate.Configuration.TypeInitializer.CompleteNames()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
         at Microsoft.Extensions.DependencyInjection.HotChocolateStitchingRequestExecutorExtensions.<>c__DisplayClass5_0.<<AddRemoteSchema>b__9>d.MoveNext()
      --- End of stack trace from previous location ---
         at HotChocolate.Execution.RequestExecutorResolver.OnConfigureSchemaBuilderAsync(ConfigurationContext context, IServiceProvider schemaServices, RequestExecutorSetup setup, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass19_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

### Additional Context?

We have reverted back to 13.5.1 as a workaround. The same remote schema is loaded fine in that version.

### Version

13.6.0

**Comment by glen-84** [comment] 2023-10-27 08:50
Duplicate of #6634.

**Comment by michaelstaib** [comment] 2023-10-28 08:30
Stitching is EOL and will be removed with the December release. We will have soon a migration guide on how to move to Fusion. For now stay on a version of stitching that worked for you.

**Closed** 2023-10-28 08:30 UTC
Labels: 🐛 bug, 🐾 duplicate, Area: Stitching
