### ISSUE TITLE
Introspection query returns a bad request

### ISSUE THREAD

**Issue by Pozoal** [ChilliCream/graphql-platform#7569] opened 2024-10-06 19:09 UTC
### Product

Banana Cake Pop

### Version

18.0.0

### Link to minimal reproduction

https://github.com/payroll-service-backend

### Steps to reproduce
**Dotnet Version 8
Hotchocolate AspNetCore 13,9.0**
1. Open any graphql project with banana cake pop version: 18.0.0
2. Once the project starts up the schema does not load and upon inspection you should realize that the introspection query fails, thus returns code 400

### What is expected?

The Introspection query is meant to return a 200

### What is actually happening?

Currently this is the error we get:
{
    "errors": [
        {
            "message": "The field isOneOf does not exist on the type __Type.",
            "locations": [
                {
                    "line": 32,
                    "column": 3
                }
            ],
            "path": [
                "__schema",
                "types"
            ],
            "extensions": {
                "type": "__Type",
                "field": "isOneOf",
                "responseName": "isOneOf",
                "specifiedBy": "http://spec.graphql.org/October2021/#sec-Field-Selections-on-Objects-Interfaces-and-Unions-Types"
            }
        }
    ]
}

### Relevant log output

```shell
{
    "errors": [
        {
            "message": "The field isOneOf does not exist on the type __Type.",
            "locations": [
                {
                    "line": 32,
                    "column": 3
                }
            ],
            "path": [
                "__schema",
                "types"
            ],
            "extensions": {
                "type": "__Type",
                "field": "isOneOf",
                "responseName": "isOneOf",
                "specifiedBy": "http://spec.graphql.org/October2021/#sec-Field-Selections-on-Objects-Interfaces-and-Unions-Types"
            }
        }
    ]
}
```

**Comment by dnetguru** [comment] 2024-10-07 00:22
Started running into this a few hours ago in BananaCakePop (as soon as the banner for upgrading to Nitro appeared). We've had no code changes deployed in the past 24 hours.

I think there might be an issue with the new introspection query.

We have worked around this by specifying the URL to our schema in the `SDL Schema Endpoint` field which bypasses introspection.

**Comment by AmbroiseCouissin** [comment] 2024-10-07 04:53
We have the same issue. We didn't update anything.

It sounds like it could be a very critical and urgent issue for quite a few people using that Nitro / ChilliCream.

**Comment by Tasteful** [comment] 2024-10-07 07:59
The issue is using the 
```
var conf = services
    .AddGraphQLServer()
    .ModifyOptions(o => o.EnableOneOf = true)
```
in combination to 
```
    public class FieldValueUpdateType : InputObjectType<FieldValueUpdate>
    {
        protected override void Configure(IInputObjectTypeDescriptor<FieldValueUpdate> descriptor)
        {
            descriptor
                .OneOf();
```

If I remove the _one of_  parts, Nitro will start work again.

**Comment by michaelstaib** [comment] 2024-10-07 09:08
We found the bug. We will issue new Hot Chocolate versions for 12, 13 and 14 today.

**Comment by Pozoal** [comment] 2024-10-07 11:11
> We found the bug. We will issue new Hot Chocolate versions for 12, 13 and 14 today.

Thank you @michaelstaib

**Comment by michaelstaib** [comment] 2024-10-08 08:20
This one is now fixed.

**Closed by michaelstaib** 2024-10-08 08:20 UTC
Labels: 🐛 bug, 🌶️ banana cake pop

**Comment by jbennink** [comment] 2024-10-08 08:33
@michaelstaib But I don't see a new release? Does the package at runtime get resources from a cdn, where the issue was.

**Comment by michaelstaib** [comment] 2024-10-08 12:03
@jbennink yes, by default nitro (former BCP) is pulled in from a CDN. In 6 years its the first time that we broke a small percentage of users. Basically only if you are using an alpha feature of the GraphQL spec. In my opinion this is a great setting as you get the newest tooling without a hassle.

However, you can pin the version that you are using like the following:

```csharp
app.MapGraphQL().WithOptions(
    new GraphQLServerOptions
    {
        Tool = {
            ServeMode = GraphQLToolServeMode.Version("18.0.0")
        }
    });
```

You can also pin it to the latest insider or prod version

```csharp
app.MapGraphQL().WithOptions(
    new GraphQLServerOptions
    {
        Tool = {
            ServeMode = GraphQLToolServeMode.Insider
        }
    });
```

For environments where you do not want things to come from a CDN you can also pin it to the embedded version.

```csharp
app.MapGraphQL().WithOptions(
    new GraphQLServerOptions
    {
        Tool = {
            ServeMode = GraphQLToolServeMode.Embedded
        }
    });
```
