### ISSUE TITLE
SSE connections showing timeout errors every 30 seconds

### ISSUE THREAD

**Issue by jbockle** [ChilliCream/graphql-platform#6478] opened 2023-08-25 18:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I'm using apollo with graphql-sse on my frontend, in a released environment I get a timeout error every 30 seconds however the subscription SSE connection should be long lived/ignored.  Is there a way to disable this for subscriptions over SSE?

### Steps to reproduce

use apollo client with graphql-sse link on a subscription

### Relevant log output

```shell
{
    "message": "The request exceeded the configured timeout of `00:00:30`.",
    "extensions": {
        "code": "HC0045"
    }
}
```
```


### Additional Context?

_No response_

### Version

13.2.1

**Comment by jbockle** [comment] 2023-08-25 19:18
btw I've been trying to reproduce this locally but have been unsuccessful, things I've tried:
- without attaching debugger and modifying request options to lower timeout to 1 second
- running app in docker with the same image

**Comment by michaelstaib** [comment] 2023-08-27 11:57
Are you doing subscriptions over SSE or other kinds of operations.

**Comment by jbockle** [comment] 2023-08-27 12:28
doing all kinds of operations, however the page I'm testing this on is only doing subscriptions, other operation types are not called

**Comment by michaelstaib** [comment] 2023-08-28 14:47
I cannot reproduce your issue.

Here is our demo subscription which will run until canceled and it will run forever in our tests.

```csharp
[SubscriptionType]
public static class Subscription
{
    public static async IAsyncEnumerable<string> Stream(CancellationToken cancellationToken)
    {
        while (!cancellationToken.IsCancellationRequested)
        {
            await Task.Delay(1000);
            yield return DateTime.UtcNow.ToString();
        }
    }

    [Subscribe(With = nameof(Stream))]
    public static string OnEvent([EventMessage] string s)
        => s; 
}
```

**Comment by jbockle** [comment] 2023-08-28 16:53
I just tried with apollo client websockets as well and seeing the same error in the messages list.  Like sse, this only occurs when deployed, can't reproduce locally.

```
{"id":"0b40c7ce-0f15-4194-b9de-9315e4c4161b","type":"error","payload":[{"message":"The request exceeded the configured timeout of \u006000:00:30\u0060.","extensions":{"code":"HC0045"}}]}
```

**Comment by jbockle** [comment] 2023-08-28 17:05
I should have stated before - the error doesn't stop the subscription from running.  In apollo client I have wired it to display error messages as a notification, I can easily ignore this specific error code for subscription operations but bringing this up as it seems like it might be an issue with the timeout pipeline itself.  Maybe the `TimeoutMiddleware` should skip subscription operations?

**Comment by michaelstaib** [comment] 2023-08-29 07:00
We need a repro not involving Apollo. We have never run into the issue. The cancellation token in the `TimeoutMiddleware` is not used within the subscription. The context is branched of and individual tokens are issued.

**Comment by glen-84** [comment] 2024-01-16 09:46
Closing, for lack of a reproduction.

**Closed by glen-84** 2024-01-16 09:46 UTC
Labels: 🔍 investigate, 🌶️ hot chocolate, needs-repro
