### ISSUE TITLE
Introspection query failing with non-authenticated request

### ISSUE THREAD

**Issue by napfernandes** [ChilliCream/graphql-platform#6853] opened 2024-01-24 17:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Banana Cake Pop

### Describe the bug

I'm adding an authorization layer on top of my GraphQL endpoints.

```C#
app.MapGraphQL().RequireAuthorization();
//...
graphQL
  .AddMutationType<MutationType>()
  .AddQueryType<QueryType>()
  .AddAuthorization();
```

However, I'm not able to leave my introspection request WITHOUT authentication.
<img width="202" alt="image" src="https://github.com/ChilliCream/graphql-platform/assets/106807879/38ce63dd-d63a-4e28-b661-45021d2d2277">

When I send an authentication token, the introspection query goes through. When I'm not sending it, it sends me a `Forbidden` back.

I've seen in your website the following statement:
```Unlike the @authorize directive this will return status code 401 and prevent unauthorized access to all middleware included in MapGraphQL. This includes our GraphQL IDE Banana Cake Pop. If we do not want to block unauthorized access to Banana Cake Pop, we can split up the MapGraphQL middleware and for example only apply the RequireAuthorization to the MapGraphQLHttp middleware.```

Even though I tried the following, it does not work:
```C#
app.MapGraphQL();
app.MapGraphQLHttp().RequireAuthorization();
```

Is there any workaround or a better way to configure that, so my introspection calls are anonymous?

Thanks!

### Steps to reproduce

1. Create a GraphQL server with the configuration above;
2. You can use JwtBearer for token validation if you want;
3. Try adding the same criteria I've added for authorization;
4. Try to open Banana Cake Pop and see the introspection call failing;
5. Try to open Banana Cake Pop, add an authorization header with a valid token, refreshes the page and you will see the introspection call going through.

### Version

13.0.5

**Comment by glen-84** [comment] 2024-01-24 18:59
Looks like a duplicate of #5435.

**Comment by glen-84** [comment] 2024-01-26 12:09
Closing as a duplicate of #5435.

**Closed by glen-84** 2024-01-26 12:09 UTC
Labels: 🐛 bug, 🐾 duplicate, 🌶️ hot chocolate
