### ISSUE TITLE
Strawberry Shake 13 - Generating client when schema has JSON scalar causes error

### ISSUE THREAD

**Issue by tomwilsond1** [ChilliCream/graphql-platform#5899] opened 2023-03-01 16:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

Generating client when schema has JSON scalar causes error

After upgrading to version 13.0.4, I'm getting the following error..

**Error GQL: An item with the same key has already been added. Key: JSON**

31>_GenerateGraphQLCode:
         dotnet "C:\WINDOWS\ServiceProfiles\NetworkService\.nuget\packages\strawberryshake.server\13.0.4\build\..\tools\net6\dotnet-graphql.dll" generate "D:\agents\agent02_dev_pr\_work\2\s\GrowFlow.ArcClient" -o "D:\agents\_work\2\s\ArcClient\obj\Release\netstandard2.0\berry" -n GrowFlow.ArcClient -a md5 -t
         Generate C# Clients started.
         Generate ArcClient started.
         Generate ArcClient completed in 332 ms

I do have a JSON scalar type in my schema defined..

"The `JSON` scalar type represents JSON values as specified by [ECMA-404](http:\/\/[www.ecma-international.org](http://www.ecma-international.org/)\/publications\/files\/ECMA-ST\/ECMA-404.pdf)."
scalar JSON

Removing the JSON scalar type from the schema fixes the build issue (edited)

### Steps to reproduce

1. Create new strawberry shake client
2. Use the schema provided below
3. Wire up SS client to schema
4. Build project
5. Get Error

schema {
  query: Query
  mutation: Mutation
}
 
type ApiRequest{
    nodeId: ID!
  id: Int! 
  body: JSON 
}

"The `JSON` scalar type represents JSON values as specified by [ECMA-404](http:\/\/www.ecma-international.org\/publications\/files\/ECMA-ST\/ECMA-404.pdf)."
scalar JSON

### Relevant log output

```shell
Error GQL: An item with the same key has already been added. Key: JSON
31>_GenerateGraphQLCode:
         dotnet "C:\WINDOWS\ServiceProfiles\NetworkService\.nuget\packages\strawberryshake.server\13.0.4\build\..\tools\net6\dotnet-graphql.dll" generate "D:\agents\agent02_dev_pr\_work\2\s\GrowFlow.ArcClient" -o "D:\agents\_work\2\s\ArcClient\obj\Release\netstandard2.0\berry" -n GrowFlow.ArcClient -a md5 -t
         Generate C# Clients started.
         Generate ArcClient started.
         Generate ArcClient completed in 332 ms
```

### Version

13.0.4

**Comment by Doytoend** [comment] 2023-03-28 07:47
Hi,

"EXEC : error GQL: An item with the same key has already been added. Key: JSON..."

Having the same issue described here. Has anyone found a workaround? I don't control the server portion and there are over 200 JSON scalars in their Schema so removing is not an option for me.

**Comment by mathewgrabau** [comment] 2023-03-31 04:28
I am also having the same issue.

**Comment by Intentivekhansen** [comment] 2023-04-12 08:57
Im getting same error and are not able ommit json scalar. Im using strapi as backend and therefore cannot remove the type. Unfortunatly using v12 wasnt working for me either.

Anyone news regarding this problem?

**Comment by joshlrogers** [comment] 2023-04-13 14:15
FYI, integrating with the Shopify GraphQL API is impossible due to this bug

**Comment by rlincoln24** [comment] 2023-04-14 00:07
First time using this package and I thought this was just me the entire time. 

Also having this exact same issue. Was able to Generate the demo with no issues but see this when I go to build:

1>EXEC : error GQL: An item with the same key has already been added. Key: JSON

Hopefully there is a fix soon, kinda stuck :(

**Comment by wujun4code** [comment] 2023-04-16 01:34
+1 case, same issue when graphql schema contains a JSON scalar type.

**Comment by gerwim** [comment] 2023-04-23 09:00
Same issue, tried to migrate from Strawberry Shake v12 to v13 which results in this error.

**Comment by ifunky** [comment] 2023-05-15 07:38
I'd really like to use this as well but can't seem to get it going like the above :-(

**Comment by kpiekara** [comment] 2023-06-04 16:51
Same here, still don't work on 13.2.0/.NET 7.

**Comment by clazarev** [comment] 2023-06-27 13:20
Hi,
I think I found the root cause of this issue. I'm creating a PR soon

**Comment by davidegolzi** [comment] 2023-10-18 15:36
@clazarev when this fix will be available?

**Comment by sfnmk** [comment] 2023-11-20 23:29
Just commenting here that I'm also affected by this bug. Using strapi back-end.

**Comment by glen-84** [comment] 2023-12-27 11:00
Closing, as I'm unable to reproduce this error using Strawberry Shake 13.8.1.

**Closed by glen-84** 2023-12-27 11:00 UTC
Labels: 🐛 bug, 🌶️ strawberry shake
