### ISSUE TITLE
Fusion doesn't work if both subgraphs and Fusion servers use authorisation

### ISSUE THREAD

**Issue by Meh3** [ChilliCream/graphql-platform#6333] opened 2023-07-09 17:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

If two subgraphs and Fusion servers use authorisation, both have ApplyPolicy defined and a conflict occurs in Fusion server.
Theoretically you can use IgnoreType when configuring Fusion Server, but it doesn't work.

### Steps to reproduce

1. Create two subgraphs servers, each with an AddAuthorisation configuration.
2. Create FusionServer also with AddAuthorisation configuration
3. Run Fusion server
4. Try to reload fusion schema in Banana Cake Pop
5. Error from log section appears

### Relevant log output

```shell
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. The name `ApplyPolicy` was already registered by another type. (HotChocolate.Authorization.ApplyPolicyType)

         at HotChocolate.Configuration.TypeRegistry.Register(String typeName, RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.CompleteTypeName(RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.<CompleteNames>b__23_0(RegisteredType type)
         at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
         at HotChocolate.Configuration.TypeInitializer.CompleteNames()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass20_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Symfonia.Admin.Api.GraphQL.Middlewares.LoadPlatformSchemaMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\TFS\Core2\src\modules\Admin\Symfonia.Admin.Api.GraphQL\Middlewares\LoadPlatformSchemaMiddleware.cs:line 43
         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Symfonia.Api.Middlewares.EnableRequestBodyBufferingMiddleware.InvokeAsync(HttpContext context) in C:\TFS\Core2\src\Symfonia.Api\Middlewares\EnableRequestBodyBufferingMiddleware.cs:line 14
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Version

13.3.1

**Comment by michaelstaib** [comment] 2023-07-11 13:58
You need to configure header propagation

**Comment by michaelstaib** [comment] 2023-07-11 14:02
https://thecodeblogger.com/2021/05/25/request-header-propagation-in-net-core-web-applications/

**Comment by Meh3** [comment] 2023-07-11 14:31
I had header propagation configured and it works fine when subgraph has authorisation and fusion server does not. The problem is when the fusion server also has authorisation. In my repro steps no request is even sent to subgraphs and problems occur. The fusion server can't even be initialised because the ApplyPolicy enum type appears twice in the fusion graph.

**Comment by Meh3** [comment] 2023-07-26 08:14
Thanks for reopening. I'm wondering if this should be marked as a bug rather than a question? 
Can you give us a rough estimate of when we can expect a fix?
Thanks

**Comment by michaelstaib** [comment] 2023-07-30 07:53
Its not a bug as we have not implemented any authorization on the fusion gateway. At the moment its not supported. With the current version authorization is supposed to be handled by the subgraph.

We have a feature for authorization on the backlog for version 13.8.

I am closing this issue as it is by design that the gateway has no authorization capabilities as of now. 

**This is expected:**
> I had header propagation configured and it works fine when subgraph has authorisation and fusion server does not.

**Closed** 2023-07-30 07:53 UTC
Labels: ❓ question, 🌶️ hot chocolate

**Comment by michaelstaib** [comment] 2023-07-30 07:55
We are also not sure yet if there should be authorization in the gateway as this would duplicate logic that is already executed on the subgraphs. We are still discussing this topic internally. Join the fusion channel on slack as we are constantly posting the current roadmap there and giving hints as to how we implement certain aspects of the roadmap.

**Comment by michaelstaib** [comment] 2023-07-30 07:55
slack.chillicream.com

**Comment by Meh3** [comment] 2023-07-30 08:13
Thanks for the answer.
I think authorisation on the fusion server side would be beneficial. It would be nice to have a global common authentication and authorisation and not have to repeat it (or use it) on every subgraph/application. So the need is to have authentication/authorisation (at least the common part) on the gateway side and not on the subgraph side.

**Comment by Meh3** [comment] 2023-07-30 08:21
Ps:
I'm writing from the perspective of a larger company that has a cloud platform and many products around it with a single point of access.

**Comment by slbentley** [comment] 2023-11-03 13:24
@michaelstaib  referring to your comment about Fusion and authorization, on Jul 30 you said authorization for fusion was on the backlog for 13.8. I see now that we've jumped from 13.7 to 14.0 preview. Does the preview have authorization? Also as far as contacting you via Slack, which you mention in your class as well as in this thread, my company does not allow slack in house so unfortunately ATM this is my best known way of communicating with you.  Any better alternatives?

**Comment by DanielASMPT** [comment] 2025-08-11 07:13
I know this isn’t exactly in context for the issue here, but while Googling for Header Propagation in GraphQL Fusion, this was the only instruction I could find. Posting it here in case it helps the next person trying to do the same.

For anyone stumbling across this while trying to set up header propagation:
In the Fusion Gateway setup, all downstream subgraph calls go through the HttpClient named "Fusion".

So adding the following to your setup will enable propagation:
```

builder.Services
    .AddHttpClient("Fusion")
    .AddHeaderPropagation();
```
