### ISSUE TITLE
Strawberry Shake: Sequence contains no elements when querying GitHub's GraphQL API for Author

### ISSUE THREAD

**Issue by pwyszyns** [ChilliCream/graphql-platform#5109] opened 2022-06-01 09:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to fetch Pull Requests information from GitHub GraphQL endpoint, however, when I add `Author` to the query, code generation breaks on build with the error `CSC : error SS0006: Sequence contains no elements`.

I have tested the same query from Thunder Client (VS code extension for HTTP calls) and it seems to be working fine, fetching the data properly.

Schema can be found [here](https://docs.github.com/en/graphql/overview/public-schema).
GraphQL endpoint: https://api.github.com/graphql

The query I'm using is as follows:
```graphql
query GetRepositoryOpenPullRequests($org: String!, $repositoryName: String!) {
  repository(owner: $org, name: $repositoryName) {
    url
    pullRequests(last: 100, states: OPEN) {
      totalCount
      nodes {
        url
        title
        state
        author {
          login
        }
        commits {
          totalCount
        }
        reviews (last: 100) {
          nodes {
            bodyText
            comments {
              totalCount
            }
            state
          }
        }
      }
    }
  }
}
```

I'm very new if it comes to GraphQL, so maybe there is an error within the query, but since it works outside of Strawberry Shake, I doubt that.

### Steps to reproduce

1. Create a new project (in my case it's web app, but I don't think it matters much)
2. Add Strawberry Shake packages and tools as per [tutorial](https://chillicream.com/docs/strawberryshake/get-started)
3. Initialize GraphQL schema
4. Try to build - build should succeed.
5. Add above query to project
6. Try to build again - build will fail with following error: 
`CSC : error SS0006: Sequence contains no elements` relating to .csproj file.
7. Remove `author { ... }` from the query
8. Try to build again - build will work.

### Relevant log output

`CSC : error SS0006: Sequence contains no elements`

### Additional Context?

I also noticed that the generated file cannot be deleted - it will be re-created in few seconds from deletion. I'm not sure if it's related though.

### Product

Strawberry Shake

### Version

12.9.0

**Comment by pwyszyns** [comment] 2022-06-20 06:48
Hi @michaelstaib I see that you've assigned yourself to this issue some time ago - were you able to reproduce it?

**Comment by mac2000** [comment] 2022-09-05 09:36
Here is an reproduction snippet:

```bash
mkdir repro
cd repro
dotnet new web
dotnet add package StrawberryShake.Transport.Http
dotnet add package StrawberryShake.CodeGeneration.CSharp.Analyzers
# dotnet tool install StrawberryShake.Tools --global
dotnet graphql init https://api.github.com/graphql -n GitHubClient --token xxxxxxxxxxxxxxxxxxxx
echo 'query Search($terms: String!) {
  search(type: ISSUE, query: $terms, first: 5) {
    nodes {
      ...on PullRequest {
        title
        author {
          login
        }
      }
    }
  }
}' > Search.graphql
dotnet build
```

which gives us: `CSC : error SS0006: Sequence contains no elements [/repro/repro.csproj]`

Or if you wish not to deal with github tokens you can skip step with init and just download schema like so:

```bash
wget https://docs.github.com/public/schema.docs.graphql -O schema.graphql
```

Also observing something similar in octokit graphql but with search in overall rather than author [275](https://github.com/octokit/octokit.graphql.net/issues/275)

**Comment by glen-84** [comment] 2024-06-06 15:34
Closing, as I'm unable to reproduce this error using Strawberry Shake 12.15.3 or 13.9.5.

**Closed by glen-84** 2024-06-06 15:34 UTC
Labels: 🐛 bug, 🌶️ strawberry shake
