### ISSUE TITLE
Inconsistent behaviour of @include directive when used with fragments

### ISSUE THREAD

**Issue by tmitchel2** [ChilliCream/graphql-platform#5970] opened 2023-03-17 14:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

This issue relates to v13, it does not occur in v12.

The following query works as expected.
```
query AppQuery {
  ...AppFragment1_query @include (if: true)
  ...AppFragment2_query @include (if: false)
}

fragment AppFragment1_query on Query {
  environment {
    name
  }
}

fragment AppFragment2_query on Query {
  environment {
    name
  }
}
```
by giving this result
```
{
  "data": {
    "environment": {
      "name": "Dev"
    }
  }
}
```

However, if i rearrange the same query by hoisting up one of the fragments like so...
```
query AppQuery {
  environment {
    name
  }
  ...AppFragment1_query @include(if: false)
}

fragment AppFragment1_query on Query {
  environment {
    name
  }
}
```
I now get the incorrect / unexpected result of
```
{
  "data": {}
}
```

This is a contrived example but in the real query I use in my app (utilising Relay as a client) it causes an issue once the data is spread out amongst the components.

### Steps to reproduce

1. Use the failing example above (2nd query above) to create a query against any schema

### Version

13.0.5

**Comment by michaelstaib** [comment] 2023-03-18 08:53
Thanks for reporting this. We did some work on include and skip and probably introduced this bug. I will have a look at this.

**Comment by michaelstaib** [comment] 2023-03-21 13:22
The issue is now fixed ... and will be merged soon ... you can track it on #5977

**Closed** 2023-03-21 21:29 UTC
Labels: 🐛 bug, 🌶️ hot chocolate, repro-validated
