### ISSUE TITLE
UseProjection does not work on UnionType

### ISSUE THREAD

**Issue by zliebersbach** [ChilliCream/graphql-platform#6312] opened 2023-07-04 05:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Expect to be able to UseProjection even when a UnionType is returned. If the resolver does not return an IQueryable then projection middleware should not do anything with the result.

### Steps to reproduce

1. Create any UnionType of ObjectTypes
```c#
public class SubmitFormResultType : UnionType
{
    protected override void Configure(IUnionTypeDescriptor descriptor)
    {
        descriptor.Name("SubmitFormResult");
        descriptor.Type<ObjectType<FormSubmission>>();
        descriptor.Type<ObjectType<FormSubmissionParseError>>();
        descriptor.Type<ObjectType<DbUpdateError>>();
        descriptor.Type<ObjectType<NotFound>>();
    }
}
```
2. Create any resolver with UseProjection that returns the UnionType
```c#
[Authorize("create:data")]
[GraphQLType<NonNullType<SubmitFormResultType>>]
// https://github.com/ChilliCream/graphql-platform/issues/5648, https://github.com/ChilliCream/graphql-platform/issues/5161
// [UseSingleOrDefault]
[UseProjection]
public static async Task<object> SubmitForm(Guid poolId, 
    SubmitFormInput input,
    IResolverContext resolverContext)
{
    // ...
    if (form is null)
    {
        return new NotFound("Form not found.");
    }

    // ...

    try
    {
        // ...
    }
    catch (FormSubmissionParseException)
    {
        // ...
        return new FormSubmissionParseError("Failed to parse form submission. Validate form templates and inputs before trying again.");
    }
    catch (DbUpdateException)
    {
        // ...
        return new DbUpdateError("Failed to save submission to the database. Validate form templates and inputs before trying again.");
    }
    // ...
    
    // https://github.com/ChilliCream/graphql-platform/issues/5648, https://github.com/ChilliCream/graphql-platform/issues/5161
    return dbContext.FormSubmissions
        .Project(resolverContext)
        .SingleAsync(x => x.Id == submission.Id);
}
```

### Relevant log output

```shell
Type \u0027Services.Data.Schema.Forms.FormSubmissionParseError\u0027 does not have a default constructor (Parameter \u0027type\u0027)\n   at System.Linq.Expressions.Expression.New(Type type)\n   at HotChocolate.Data.Projections.Expressions.QueryableProjectionScopeExtensions.CreateMemberInit(QueryableProjectionScope scope)\n   at HotChocolate.Data.Projections.Expressions.QueryableProjectionScopeExtensions.CreateMemberInitLambda(QueryableProjectionScope scope)\n   at HotChocolate.Data.Projections.Expressions.QueryableProjectionScopeExtensions.Project[T](QueryableProjectionScope scope)\n   at HotChocolate.Data.Projections.Expressions.QueryableProjectionContextExtensions.Project[T](QueryableProjectionContext context)\n   at HotChocolate.Data.Projections.Expressions.QueryableProjectionProvider.\u003CCreateApplicator\u003Eb__7_0[TEntityType](IResolverContext context, Object input)\n   at HotChocolate.Data.QueryableProjectExtensions.ExecuteProject[T](T input, IResolverContext context, Type expectedType)\n   at HotChocolate.Data.QueryableProjectExtensions.Project[T](IQueryable\u00601 queryable, IResolverContext context)
```

### Additional Context?

Reason I am not using `[UseSingleOrDefault]`: https://github.com/ChilliCream/graphql-platform/issues/5648, https://github.com/ChilliCream/graphql-platform/issues/5161

### Version

13.2.1

**Comment by glen-84** [comment] 2024-01-20 14:41
Just curious, is `FormSubmissionParseError` a class or a record?

**Comment by zliebersbach** [comment] 2024-01-21 10:28
> Just curious, is `FormSubmissionParseError` a class or a record?

It's a record.

**Comment by glen-84** [comment] 2024-01-21 10:46
This might be the same as #6487 then. Does it work if you use a class?

**Comment by glen-84** [comment] 2024-02-25 11:56
Closing as a duplicate of #6487.

**Closed by glen-84** 2024-02-25 11:56 UTC
Labels: 🐛 bug, 🐾 duplicate, 🌶️ hot chocolate, Area: Projections
