### ISSUE TITLE
BCP mutation in firefox has incorrect request

### ISSUE THREAD

**Issue by Arrivegrsmith** [ChilliCream/graphql-platform#6060] opened 2023-04-17 17:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Banana Cake Pop

### Describe the bug

<img width="1532" alt="Screenshot 2023-04-17 at 12 18 35 PM" src="https://user-images.githubusercontent.com/105511290/232562107-2651a548-5e27-4901-a558-c840d6878e30.png">
Running a mutation creates an incorrect post body. Issue is not present in chrome, only in firefox.

### Steps to reproduce

1. Create mutation in BCP in Firefox 112.0.1
2. Observe mutation request is malformed

### Additional Context?

MacOS Ventura 13.2.1
Firefox 112.0.1
dotnet 7
HC 13.0.5 with inbuild BCP

### Version

HC 13.0.5

**Comment by rstaib** [comment] 2023-04-18 08:08
@Arrivegrsmith could you please provide the version of BCP. For that, click on the `?` icon on the left side of the footer. Thanks in advance.

**Comment by rstaib** [comment] 2023-04-18 08:08
By the way in the latest version of BCP `5.0.0`, I cannot reproduce this issue.

**Comment by rstaib** [comment] 2023-04-18 08:09
And my I also ask which `Run` button you clicked?

**Comment by glen-84** [comment] 2024-01-18 10:31
> Using firefox's "Clear cookies and site data..." under the padlock on the URL cleared the initial reported issue!

Closing, as the initial issue appears to have been resolved.

> There is another issue discovered in incognito mode while debugging. An error is presented immediately on page load. This popup error does not exist in chrome's incognito mode. Should this be a separate ticket?

Yes please, if you're still able to reproduce the error.

**Closed by glen-84** 2024-01-18 10:31 UTC
Labels: 🐛 bug, 🌶️ banana cake pop
