### ISSUE TITLE
WebSocket Authentication issues. WebSocket base class does not have a definition for Options which is needed for Authentication. 

### ISSUE THREAD

**Issue by Brutiquzz** [ChilliCream/graphql-platform#6982] opened 2024-03-11 14:41 UTC
### Product

Strawberry Shake

### Version

13.9.0

### Link to minimal reproduction

This is not possible. 

### Steps to reproduce

Documentation mentions in order to authenticate websocket client:
![image](https://github.com/ChilliCream/graphql-platform/assets/33770011/67c01077-7c78-4c70-9fb0-0803c73496cb)

However PR [4789](https://github.com/ChilliCream/graphql-platform/commit/6b7ae043c387371fb1f8813d7249a26613053345#diff-2e6835ec95782ea3af30599bb63452c4fcd424f6a139f6ca97ad69e0bc8b6880) has introduced this change:

![image](https://github.com/ChilliCream/graphql-platform/assets/33770011/c30a30e3-d5b9-41a4-9d9c-1d2b24ab885d)

Forcing us to cast to ClientWebSocket because the Options property does not exist on the base WebSocket class
````
            var token = await GetAuthenticationToken();
            serviceCollection
                .AddSomeNiceClient()
                .ConfigureHttpClient(client =>
                {
                    client.BaseAddress = new Uri("https://some-none-localhost-url/graphql");
                    client.DefaultRequestHeaders.Add("Authorization", $"Bearer {token}");
                })
                .ConfigureWebSocketClient(client =>
                {
                    client.Uri = new Uri("wss://some-none-localhost-url/graphql/ws");
                    ((ClientWebSocket)client.Socket).Options.SetRequestHeader("Authorization", $"Bearer {token}");
                });
````

I do still get an exception that I am in doubt if is due to issues in the StrawberryShake or my setup
![image](https://github.com/ChilliCream/graphql-platform/assets/33770011/03bea929-e675-41e6-b6f3-968b54ce8a41)

### What is expected?

I expect authentication to happen and events coming through

### What is actually happening?

Nothing except exception thrown

### Additional context

I do successfully run queries and mutations using the http client setup.

**Comment by glen-84** [comment] 2024-03-11 17:54
Duplicate of #6052.

**Closed by glen-84** 2024-03-11 17:54 UTC
Labels: 🐛 bug, 🐾 duplicate, 🌶️ strawberry shake
