### ISSUE TITLE
Subscription stitching feature throws exception

### ISSUE THREAD

**Issue by stuartjbrown** [ChilliCream/graphql-platform#5074] opened 2022-05-17 14:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Regarding the comment in issue https://github.com/ChilliCream/hotchocolate/issues/562#issuecomment-1046890411, this implies that subscription stitching should automatically work but at least in HC13-preview.19 this isn't the case for me.  I get the following error when I try and subscribe to a subscription for a GQL server using those options.

The exception I get is shown in the log output - this implies that there is a step missing adding an `ISocketClientFactory` to services.  The interface of the same name in StrawberryShake doesn't appear to be compatible (different interface signatures).  

Is the subscription stitching feature complete?  Is there something still missing or do I need some manual configuration?  It would be great to know that before I invest further hours in testing this. Thanks!

### Steps to reproduce

1. Setup a stitching server and add a remote schema with the option: `capabilities: new HotChocolate.Stitching.EndpointCapabilities {
                    Subscriptions = HotChocolate.Stitching.SubscriptionSupport.WebSocket,
                                        Batching = BatchingSupport.RequestBatching
                }`
2. Attempting to subscribe to a working subscription on the end server throws an error

### Relevant log output

```shell
System.InvalidOperationException: No service for type 'HotChocolate.Stitching.Execution.ISocketClientFactory' has been registered.
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.HotChocolateStitchingRequestExecutorExtensions.<>c__DisplayClass3_0.<AddRemoteSchema>b__4(IServiceProvider sp)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices[T](IServiceProvider provider)
         at HotChocolate.Stitching.Execution.RemoteRequestExecutor..ctor(AutoUpdateRequestExecutorProxy innerExecutor)
         at Microsoft.Extensions.DependencyInjection.HotChocolateStitchingRequestExecutorExtensions.<>c__DisplayClass3_0.<<AddRemoteSchema>b__3>d.MoveNext()
```

### Product

Hot Chocolate

### Version

13.0.0-preview.19

**Comment by PascalSenn** [comment] 2022-05-17 17:21
Stitching is actively worked on. It's likely that parts of stitching in the previews do not work. Once v13 reaches stable subscription stitching will work. 
Thanks for reporting though :)

**Comment by stuartjbrown** [comment] 2022-05-30 08:43
> Stitching is actively worked on. It's likely that parts of stitching in the previews do not work. Once v13 reaches stable subscription stitching will work.
> Thanks for reporting though :)

Thanks for the update Pascal.  As the subscription stitching and graphql-ws features were marked as done in the release, we thought to give it a try.  But we will wait for the final version before testing again :)

**Comment by Psypher9** [comment] 2022-12-05 17:42
I've looked over the comment on #562 and also here, but I do not see where there is an `AddRemoteSchema` overload which accepts an `EndpointCapabilities` object. Where is that overload coming from?

**Comment by michaelstaib** [comment] 2023-01-12 09:40
We have moved this feature to 13.1 ... I am closing this issue since we are actively working on this.

**Closed by michaelstaib** 2023-01-12 09:40 UTC
Labels: 🐛 bug

**Comment by DanielHofer001** [comment] 2023-04-13 06:48
Hi @michaelstaib and all the others,

I created a small example for reproducing the error with subscription and federated schema. Is there any way to fix this (I also tried 12, 13, and 14 preview versions, but could not find a working solution).

Thanks in advance 

https://github.com/DanielHofer001/federated-subscriptions-hotchocolate

**Comment by michaelstaib** [comment] 2023-04-13 08:21
HotChocolate.Fusion replaces stitching and in 14 it supports stitching.

**Comment by michaelstaib** [comment] 2023-04-13 08:22
We are in a closed beta on this ping me on slack.Chillicream.com and I add you to the fusion channel.

**Comment by DanielHofer001** [comment] 2023-05-04 08:25
Thanks for the response, but the fusion example without documentation is way to complicate to adopt it (now it reads some zip file, in previous version, subscription worked, but mutations did not - no complain, I understand it is in preview and not yet released...) 
So is there no way to create subscriptions in federated schema in the latest current stable hotchocolate version 13.05?
