### ISSUE TITLE
`IdOperationFilterInputType` not used when a field is configured as an ID using code-first

### ISSUE THREAD

**Issue by glen-84** [ChilliCream/graphql-platform#5936] opened 2023-03-07 16:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When using the `[ID]` attribute on a property, the `IdOperationFilterInputType` is correctly used.

When using `descriptor.ID()`, the `IdOperationFilterInputType` is _not_ used.

I would expect these to be equivalent.

### Steps to reproduce

1. Call `descriptor.ID()` on a property.
2. Note that a filter based on the underlying type is used, instead of the `IdOperationFilterInputType`.

### Version

13.0.2

**Comment by glen-84** [comment] 2023-03-08 12:44
@PascalSenn

That's a lot of work for every case -- is it not possible to access this metadata, I assume [here](https://github.com/ChilliCream/graphql-platform/blob/bbb93f80f31932079afdbcda5d2593adcf632049/src/HotChocolate/Data/src/Data/Filters/Convention/FilterTypeInterceptor.cs#L44-L51)?

**Comment by michaelstaib** [comment] 2023-03-08 20:24
We could implement it as a feature at some point. I am closing this as its not a bug and our work pipeline is fill with other things.

**Closed by michaelstaib** 2023-03-08 20:24 UTC
Labels: ❓ question, 🌶️ hot chocolate
