### ISSUE TITLE
StrawberryShake: Mutation containing input with a lowercase-named enum type fails generate code (Sequence contains no matching element)

### ISSUE THREAD

**Issue by gerwim** [ChilliCream/graphql-platform#4992] opened 2022-04-21 19:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Error when building the project when an input field containing an enum starts with a lowercase letter.

This issue was fixed before (https://github.com/ChilliCream/hotchocolate/issues/3704) but I can still reproduce this with the latest version (12.7.0 -- also with 12.5.0 (which was the fixed version according to the linked issue above)).

### Steps to reproduce

1. Create a mutation:
```
mutation InsertProtocol ($name: String!, $type: protocolTypes_enum!, $fileUrl: String!) {
    insert_protocols_one(object: {
        name: $name,
        type: $type,
        fileUrl: $fileUrl,
    })
    {
        id
    }
}
```
2. Use the following schema: [schema.graphql.txt](https://github.com/ChilliCream/hotchocolate/files/8534398/schema.graphql.txt)
3. Generate code
4. Will error with `Sequence contains no matching element`

If you change all `protocolTypes_enum` to `ProtocolTypes_enum`, the build succeeds.

### Relevant log output

```
Sequence contains no matching element
```

### Additional Context?

Related issue:
https://github.com/ChilliCream/hotchocolate/issues/3704

### Product

Strawberry Shake

### Version

12.7.0

**Comment by gerwim** [comment] 2022-06-28 12:38
Re-open.

**Comment by gerwim** [comment] 2022-11-04 16:08
This issue is still present.

**Comment by grounzero** [comment] 2023-01-12 14:17
I'm experiencing the same issue as well.

**Comment by glen-84** [comment] 2024-01-12 14:10
Closing as a duplicate of #3704, which has since been reopened.

**Closed by glen-84** 2024-01-12 14:10 UTC
Labels: 🐛 bug, 🐾 duplicate, 🌶️ strawberry shake
