### ISSUE TITLE
```dotnet graphql update``` throws an Unhandled exception error

### ISSUE THREAD

**Issue by Bahri-Haythem** [ChilliCream/graphql-platform#6745] opened 2023-12-04 11:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

When I try to use strawberryshake.tools command ```dotnet graphql update```, I get an Unhandled exception error. The init and download command works fine.
### schema.graphql
```
schema {
  query: Query
}

type Query {
  test: String!
}

// other code removed for brevity
```
### TestQuery.graphql
```
query Test{
  test
}
```
The query just returns a simple string: ```public string Test => "this is a test";```

### Steps to reproduce

1. In the console navigate to the project where StrawberryShake is implemented
2. run ```dotnet graphql update```

### Relevant log output

```shell
Unhandled exception. Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: ?. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at StrawberryShake.Tools.Configuration.GraphQLConfig.FromJson(String json) in /home/runner/work/graphql-platform/graphql-platform/src/StrawberryShake/Tooling/src/Configuration/GraphQLConfig.cs:line 46
   at StrawberryShake.Tools.UpdateCommandHandler.UpdateSingleSchemaAsync(UpdateComman   at StrawberryShake.Tools.UpdateCommandHandler.UpdateSingleSchemaAsync(UpdateComman   at StrawberryShake.Tools.UpdateCommandHandler.UpdateSingleSchemaAsync(UpdateCommandContext context, String clientDirectory, CancellationToken cancellationToken) in /home/runner/work/graphql-platform/graphql-platform/src/StrawberryShake/Tooling/src/dotnet-graphql/UpdateCommandHandler.cs:line 83
   at StrawberryShake.Tools.UpdateCommandHandler.ExecuteAsync(UpdateCommandArguments arguments, CancellationToken cancellationToken) in /home/runner/work/graphql-platform/graphql-platform/src/StrawberryShake/Tooling/src/dotnet-graphql/UpdateCommandHandler.cs:line 46
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at StrawberryShake.Tools.Program.<Main>(String[] args)
```

### Additional Context?

As a workaround I am using init each time to update the schema.graphql file but that changes the .graphqlrc.json each time 

### Version

13.7.0

**Comment by glen-84** [comment] 2023-12-05 12:53
Do you have a reproduction repository?

**Comment by glen-84** [comment] 2023-12-05 13:01
Might be caused by a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark). Try saving the schema files as UTF-8 without BOM.

**Comment by Bahri-Haythem** [comment] 2023-12-05 13:22
This is a reproduction [repo](https://github.com/Bahri-Haythem/GraphQLDemo.git) I made while trying to learn strawberry shake. All the files were generated with the init command I am not supposed to change their encoding.

**Comment by glen-84** [comment] 2023-12-05 13:40
@michaelstaib @tobias-tengler

Could this be resolved by #4925? I'm very surprised that this hasn't come up before (for Strawberry Shake).

**Comment by kevinoneill** [comment] 2023-12-06 01:05
I can confirm that removing the bom on the generated `.graphqlrc.json` resolved the issue for me. Adding the bom back in reproduced the error.

**Comment by rick-micpoint** [comment] 2023-12-06 10:10
Ran into this just now as well. If I didn't find this github issue I would have been completely stuck. Probably good to hotfix quickly.

**Comment by michaelraue** [comment] 2023-12-09 22:52
Can confirm the problem and the solution by @Bahri-Haythem

**Comment by glen-84** [comment] 2023-12-10 08:28
#6751 has been merged, so in the next release, the files will be written without a BOM.

**Comment by glen-84** [comment] 2023-12-12 09:09
Fixed in [13.8.0-preview.1](https://github.com/ChilliCream/graphql-platform/releases/tag/13.8.0-preview.1) and [14.0.0-p.16](https://github.com/ChilliCream/graphql-platform/releases/tag/14.0.0-p.16).

**Closed by glen-84** 2023-12-12 09:09 UTC
Labels: 🐛 bug, 🌶️ strawberry shake

**Comment by RichardWhitfield** [comment] 2024-08-08 21:25
I am still having this issue in version 13.9.9

**Comment by glen-84** [comment] 2024-08-09 08:27
@RichardWhitfield Please create a minimal reproduction of the issue.
