### ISSUE TITLE
Enable checking http status code on operation result

### ISSUE THREAD

**Issue by AlexKubiesa** [ChilliCream/graphql-platform#4906] opened 2022-03-29 14:05 UTC
### Is your feature request related to a problem?

I am writing some integration tests for a GraphQL API and I want to test that the http status code is set appropriately (e.g. 401 for authentication errors). Currently there doesn't seem to be a way to do this with a generated Strawberry Shake client.

### The solution you'd like

Add a property to `IOperationResult<T>` which stores the http status code returned by the server.

### Product

Strawberry Shake

**Comment by SeijiSuenaga** [comment] 2022-08-25 01:55
+1, I found this issue because I'm seeing a somewhat unhelpful exception from the Strawberry Shake generated client when the API returns 401 Unauthorized, for example when the API uses `RequireAuthorization()` and I send a request with no `Authorization` header.
```text
System.ArgumentNullException: 'Either body or exception have to be set.'
   at StrawberryShake.OperationResult`1..ctor(T data, IOperationResultDataInfo dataInfo, IOperationResultDataFactory`1 dataFactory, IReadOnlyList`1 errors, IReadOnlyDictionary`2 extensions, IReadOnlyDictionary`2 contextData)
   at StrawberryShake.OperationResultBuilder`1.Build(Response`1 response)
   at StrawberryShake.StorelessOperationExecutor`2.<ExecuteAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StrawberryShake.StorelessOperationExecutor`2.<ExecuteAsync>d__4.MoveNext()
```
Ideally, in this scenario the client would return a result (or throw an exception) clearly indicating that a 401 occurred.

**Comment by AlexKubiesa** [comment] 2023-11-28 14:23
Just came across this issue again. A client of our API mentioned a regression where unauthorized requests now get 500 instead of 401. If we could check the http status code via Strawberry Shake, we could easily add this check to some of our auto tests.

**Comment by glen-84** [comment] 2024-06-12 13:42
Closing as a duplicate of #4759.

**Closed by glen-84** 2024-06-12 13:42 UTC
Labels: 🎉 enhancement, 🌶️ strawberry shake
