### ISSUE TITLE
JsonElement should map to `JsonType` not `JsonType!`

### ISSUE THREAD

**Issue by onionhammer** [ChilliCream/graphql-platform#6671] opened 2023-11-03 18:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

`JsonElement` and other types that utilize it allow for `null` values on the .NET side;

for example:
```C#
using System.Text.Json;

var elem = JsonSerializer.Deserialize<JsonElement>("null");
elem // elem is NOT null, its `ValueKind` is `Null`
```

However, in HotChocolate by default, JsonElement becomes a non-null JsonType scalar.

```C#
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Test;

[MutationType]
public class TestMutation
{
    public MyInputType TakeFlexibleInput(MyInputType test)
    {
        return test;
    }
}


public class MyInputType
{
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }
}
```

yields a schema like

```graphql
type Mutation {
  takeFlexibleInput(input: TakeFlexibleInputInput!): TakeFlexibleInputPayload!
}

type MyInputType {
  extensionData: [KeyValuePairOfStringAndJsonElement!]
}

input KeyValuePairOfStringAndJsonElementInput {
  key: String!
  value: JSON!
}
```

Which does not allow for null values within the extension data, meaning any valid `null` JSON value will turn into a hot chocolate validation error.

### Steps to reproduce

1. Utilize above code
2. Post a mutation with a `null` in the list of values, i.e. `{ "myField": null }`

### Additional Context?

Other things I tried:

1. Decorating ExtensionData with JsonElement? fails because .NET's JsonSerializer doesnt accept that, it gives: "".ExtensionData' is invalid. It must implement 'IDictionary<string, JsonElement>' or 'IDictionary<string, object>', or be 'JsonObject'.""

2. `.BindRuntimeType<IDictionary<string, JsonElement>, JsonType>()` gives an array of non-null JSON values, which will not serialize well to a dictionary, also it is still non-null only

Workaround:

Perhaps create a custom json 'dictionary' scalar?

### Version

13.5.1

**Comment by glen-84** [comment] 2024-07-30 09:24
I'm not able to reproduce this issue if I change `Dictionary<string, JsonElement>?` to `Dictionary<string, JsonElement?>?` and post the following mutation:

```graphql
mutation {
  takeFlexibleInput(test: { extensionData: [{ key: "x", value: null }] }) {
    extensionData {
      key
      value
    }
  }
}
```

Am I missing something?

**Comment by onionhammer** [comment] 2024-07-30 14:52
@glen-84 JsonElement can represent `null` JSON as a valid value, so just because `JsonElement` is NOT null, doesnt mean that the JSON is NOT null.

**Comment by michaelstaib** [comment] 2024-07-31 08:11
There is no map semantic in GraphQL ... the dictionary is just a list to Hot Chocolate. Also I would not expose dictionaries like that... rather expose the map itself as JsonType and get a cleaner schema. I am closing this issue.

**Closed by michaelstaib** 2024-07-31 08:11 UTC
Labels: 🔍 investigate, 🌶️ hot chocolate

**Comment by onionhammer** [comment] 2024-07-31 13:16
@michaelstaib it's not me that's choosing JsonExtensionData as a dictionary
