### ISSUE TITLE
dotnet tooling's Download/Update omits deprecated properties even tho server introspection includes "includeDeprecated"

### ISSUE THREAD

**Issue by nlz242** [ChilliCream/graphql-platform#6836] opened 2024-01-17 20:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

Whenever I update a GraphQL schema using `dotnet graphql update` or `dotnet graphql download URL`, the properties that are marked as deprecated (using the GraphQLDeprecated attribute) are removed from my schema.

I've looked around in the code and found that the strawberryshake tooling uses HotChocolate IntrospectionClient to get the schema and that it is supposed to call the introspection query to know if it should include deprecated properties.

I've executed the query manually to confirm that my server does indeed return "includeDeprecated" as seen in this screenshot : 
![image](https://github.com/ChilliCream/graphql-platform/assets/3332745/a0561fed-afde-4a7d-8915-484294eaa7f7)

However, the client still excludes them and they get removed from my schema.

Relevant code : 
https://github.com/ChilliCream/graphql-platform/blob/d9cbd6b8d21323d0bd2e33ff78fb6e9508e03dc7/src/StrawberryShake/Tooling/src/dotnet-graphql/IntrospectionHelper.cs#L22C63-L22C63

https://github.com/ChilliCream/graphql-platform/blob/d9cbd6b8d21323d0bd2e33ff78fb6e9508e03dc7/src/HotChocolate/Utilities/src/Utilities.Introspection/IntrospectionClient.cs#L129

This seems like a bug but also points to a missing feature... the tooling should have a switch to override this behavior. 
Why should the server decide that the client is no longer allowed to use/generate properties that are marked as deprecated but not yet removed ? We use the attribute to communicate, between teams, that properties are gonna be removed eventually but it shouldn't -force- them to change a bunch of stuff when they update the schema for an unrelated reason...

### Steps to reproduce

1. Add a GraphQLDeprecated attribute to a property of an object on the server
2. Run "dotnet graphql update" on the client-side
3. Notice the property that was marked as deprecated is no longer in the schema, even if the introspection query specify that it should be included.

### Version

Tested in 13.7.0, 13.8.1

**Comment by glen-84** [comment] 2024-01-25 09:22
I'm not able to reproduce this issue: https://github.com/glen-84/hc-6836.

The deprecated `title` field is included in the schema and the client.

Am I missing something?

**Comment by nlz242** [comment] 2024-01-25 13:35
I'll work on a repro outside of our main projects and will report back.

**Comment by glen-84** [comment] 2024-02-25 12:02
Closing, for lack of a minimal reproduction.

**Closed by glen-84** 2024-02-25 12:02 UTC
Labels: 🐛 bug, 🌶️ strawberry shake, needs-repro
