### ISSUE TITLE
Conditional projections on field resolvers

### ISSUE THREAD

**Issue by moander** [ChilliCream/graphql-platform#6690] opened 2023-11-10 22:02 UTC
### Product

Hot Chocolate

### Is your feature request related to a problem?

I want to avoid selecting `FirstName` and `LastName` from the database unless `FullName` is requested in the query.

```cs

public class Person : ObjectType<Person>
{
    public long Id { get; set; }

    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    public string GetFullName([Parent] Person parent)
    {
        return $"{parent.FirstName} {parent.LastName}";
    }

    protected override void Configure(IObjectTypeDescriptor<Person> descriptor)
    {
        // This one is ok because we always wan't the id
        descriptor.Field(f => f.Id).IsProjected();

        // Problem now is that GetFullName() require FirstName and LastName to be always projected..
        descriptor.Field(f => f.FirstName).IsProjected();
        descriptor.Field(f => f.LastName).IsProjected();

    }
}
```

### The solution you'd like

```cs
public class Person : ObjectType<Person>
{
    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    // Annotation-based
    [RequireProjectedField(nameof(FirstName))]
    [RequireProjectedField(nameof(LastName))]
    public string GetFullName([Parent] Person parent)
    {
        return $"{parent.FirstName} {parent.LastName}";
    }

    // Code-first
    protected override void Configure(IObjectTypeDescriptor<Person> descriptor)
    {

        descriptor.Field(f => f.GetFullName(default!))
            .RequireProjectedField(nameof(FirstName))
            .RequireProjectedField(nameof(LastName))
    }
}
```

**Comment by glen-84** [comment] 2023-11-11 09:28
Duplicate of #2575.

**Closed** 2023-11-12 12:50 UTC
Labels: 🐾 duplicate, 🎉 enhancement, 🌶️ hot chocolate, Area: Projections
